- doc/source/sep/SEP15.md
Some links to URLs to sardana-controls.org are wrong (in the SEP15.md):
- they use https but RTD does not support that (and therefore, some browsers warn)
- the SEP index URL must end with a slash
@zreszela, could you review this?
> Fix RTD URLS

- src/sardana/pool/poolcontrollers/HklPseudoMotorController.py
The physical positions used for updating the hkl geometry were taking from cache, this could be
a problem if  the physical motors are moved outside from sardana. This PR forces the readout to
be done always from the hardware.
> HklController: Forcing read position from hardware

- .bumpversion.cfg
- src/sardana/release.py
- src/sardana/spock/ipython_00_10/genutils.py
- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
- src/sardana/spock/release.py
Add bumpversion configuration to update the version using the
bumpversion script from https://github.com/peritus/bumpversion
Deprecate the version_info and revision variables from the
sardana.release module.
> Add bumpversion support (and bump version to 2.1.2-dev)

- src/sardana/spock/ipython_00_10/genutils.py
- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
Spock upgrade fails with alpha releases.
Fix it.
Spock will be upgraded if the spock profile version
and the spock library version does not correspond.
A version containing alpha and another not containing alpha
are considered different versions.
> Issue 403: upgrade spock if versions are not equal

- src/sardana/macroserver/msparameter.py
Fix bug 407.
When using execMacro with repeat parameters, the default values
are not taken into account correctly.
This commit fixes the bug.
> Fix issue407: default values for repeat parameters

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/parameditors.py
Set tooltip to parameter's description in the ParamBase class.
Invert order of the constructor calls so the ParamBase constructor is called
when the QtWidget initialization is already done.
> Fix bug-457 (SF): show tooltip with description of params

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
MacroButton fails to execute macros which its argument is a string with spaces
> Fix bug#423 Macrobutton fails parsing string param. with spaces

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
The code enables to execute any macro (except param repeat
with multiple values) from a macrobutton. Two arguments
are required to initalize the widget: door name and macro name.
Once the widget is running, the macro name can be changed and
the interface to supply the parameters is updated automatically.
> Improve main in macrobutton.py module

- doc/source/devel/howto_macros/macros_general.rst
- src/sardana/macroserver/macros/examples/parameters.py
- src/sardana/spock/spockms.py
- src/sardana/taurus/core/tango/sardana/macro.py
- src/sardana/taurus/core/tango/sardana/macroserver.py
- src/sardana/taurus/core/tango/sardana/test/__init__.py
- src/sardana/taurus/core/tango/sardana/test/paramdef.py
- src/sardana/taurus/core/tango/sardana/test/test_macro.py
Hello,
I have done a first implementation for extending the new ParamRepeat interface to spock.
The old spock input syntax is , of course, still valid and, as before, only admit ParamRepeat parameters in the last position. With the new interface the ParamRepeat parameters can be used at any position and even recursively. I have choosen the syntax using square brackets as group characters and space as separator e.g.
mv [[mot01 5] [mot02 10]]
pt10 [0 5 10] mot01
pt11 ct01 [10 5 0] mot01
pt12 [0 5 10] [mot01 mot02 mot03]
pt13 [[mot01 mot02 mot03] [mot04 mot05]]
Everything is, of course, open to discussion, this is only a first attempt. 
Regards,
Teresa
> New ParamRepeat interface in spock

- src/sardana/macroserver/msmacromanager.py
- src/sardana/macroserver/msparameter.py
Hi, this PR should solve the issue #408, allowing to use brackets for the single element paramrepeat
arguments. 
For example a macro like:
```
class pt20_default(Macro):
"""Macro with a list of numbers as parameter."""
param_def = [
[ 'numb_list', [ [ 'pos', Type.Float, 3.0, 'value'] ], None, 'List of values'],
]
def run(self, *args, **kwargs):
self.output(args)
pass
```
Could be called like:
```
params = ('pt20_default', [1, 2, 3])
self.execMacro(params)
```
or
```
params = ('pt20_default', [1, 2, [3]])
self.execMacro(params)
```
Also the issue with the default values should be solved, so one could use:
```
params = ('pt20_default', [1, 2, []])
self.execMacro(params)
```
The issue with the default values should be solved in general, also for ParamRepeat with several elements. For …
> Accepting brackets for single paramrepeat and default values

- src/sardana/spock/parser.py
- src/sardana/spock/test/test_parser.py
Use negative lookbehind assertion in the regular expression describing
quoted parameter in order to allow passing quotes escaped by backslash.
Also avoid string cutting in order to exclude quotes and single quotes
from the string parameters. Do it by explicit extraction of the given group.
> Fix #442: allow escaped quotes in parameters (spock)

- .travis.yml
- ci/flake8_diff.sh
Implements flake8 check on the diff e.g. only on the changes introduced in the pull request. In case the pull request is not flake8 compliant (PEP8 and others) it fails the travis-ci. The tests are run anyway.
Apart of that the included script has more applications - see documentation.
> Add flake8 check on diff to travis-ci

- src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
Revert implementation to what was present prior 6b5b58e (removing units).
This logic does not have too much sense - timer is not used to control the 0D
chennel but at least it does not provoke exception.
> Fix #448: expconf problem with timers of 0D

- src/sardana/tango/pool/OneDExpChannel.py
- src/sardana/tango/pool/TwoDExpChannel.py
We found a, I guess, copy-paste bug in the read_Value function of the TwoD and OneD experimental channels, introduced with the sep6 implementation. This PR only correct the copy-paste error.
> Copy-paste bug in read_Value function

- src/sardana/macroserver/macros/standard.py
Motor's position attribute stays subscribed in case an exception occurs while
executing the move. Enclose the move with try/finally clause so we unsubscribe in case
of the exception as well as in case of a normal end of movement.
> Fix #464: umv unsubscribe in case of exception

- src/sardana/macroserver/macros/standard.py
- src/sardana/taurus/core/tango/sardana/pool.py
This is a very simple fix of #467 and a PEP8-ification of the module the error was in.
Also, when I've printed that value of `state` variable that caused the exception here, I got what I've reported in #456 , so:
```
["TypeError: 'TaurusDevState' object is not callable\n"]
```
But I guess that that is another issue. Only now have I learned why I've seen it and not the exception: it turns out that @daneos has hot-fixed it.
> Fix #467 - catching and handling exception in a motion ending in alarm

- ci/flake8_diff.sh
The flake8_diff.sh script is a custom wrapper on flake8 used for
CI, but also locally for performing checks before pushing.
Add support for passing arguments to flake8_diff.sh so that it
propagates them to flake8 (useful e.g. if your local version of
flake8 behaves differently to that in the CI machine).
> Accept additional args in flake8_diff.sh

- setup.py
- src/sardana/macroserver/msmacromanager.py
- src/sardana/macroserver/msrecordermanager.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/poolaction.py
- src/sardana/pool/poolcontrollermanager.py
- src/sardana/sardanabuffer.py
Sardana imports OrderedDict module from taurus.external and it will
be dropped in the next release.
Fix #481
> Avoid import OrderedDict from taurus

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
A string value is expected as argument for updateMacroArgument
method. However, this value comes from any valid signal and
could be any other object.
Remove the regular expression statement before string conversion.
> Fix bug when updating macro arguments

- src/sardana/tools/config/get_pool_config.py
get_pool_config fails with Pools that define TriggerGate elements. Fix it.
> Make get_pool_config compatible with TriggerGate

- src/sardana/pool/poolcontrollers/DummyOneDController.py
- src/sardana/tango/pool/PoolDevice.py
In https://github.com/sardana-org/sardana/issues/487#issuecomment-312236540 @LJBD pointed a possible solution for serializing numpy arrays. However it is quite complex to implement having in mind that we are serializing a more complex data structure that at the moment contains a multiple indexes and multiple values. IMHO it will be quite difficult to serialize it and deserialize it in this way.
A simple `ndarray.tolist` before serializing works well and for arrays of < 10k elements its performance is similar. So I propose to solve it in this way until we find time to optimize it.
Fixes #487
> Fix 1D's returning numpy arrays

- src/sardana/macroserver/macros/scan.py
- src/sardana/macroserver/recorders/output.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/poolbasegroup.py
- src/sardana/tango/pool/test/base_sartest.py
- src/sardana/taurus/core/tango/sardana/pool.py
- src/sardana/taurus/core/tango/sardana/test/test_pool.py
This PR provides timescan (solves #104).
In order to reuse as much as possible from the existing scan framework I made a decision to relax the “motion” requirements of the `GScan` class so it could be used in scans which do not involve moveables. An alternative solution that I have evaluated was to develop a lower level abstract class e.g. `BaseScan` that would just take care of the basic scan setup and leave the `GScan` strongly linked to the “motion” concepts. I was not sure if this refactoring is really necessary and I consider it more complicated to implement, that’s why I decided to leave only the `GScan` class. But of course we can still do this refactoring in the future, if necessary.
The summary of changes:
- `timescan` macro was added that executes equidistant time scans.
- …
> Add timescan

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
Macroexecutor raises an Attribute error if you try to execute
a "favorite macro" after restarting the macroexecutor.
Fix #441 
The flake8 could fail cause a URL in a comment  exceed the 79 characters
> Fix Problem in loading a favorite macro in macroexecutor

- ci/appveyor.yml
Add appveyor.yml file to generate sardana artifacts on windows.
A project configuration may be required. Enabling and configuring appveyor 
using an admin user.
> Configure CI service for Windows (appveyor)

- src/sardana/taurus/core/tango/sardana/macro.py
This PR fixes #366. I did not find a way to print multiple outputs with a line magic in IPython. So multiple results are encapsulated in a tuple and printed on one output.
@cmft could you check if it works for you now and feedback.
> Print multiple macro results in spock - fix #366

- src/sardana/macroserver/macro.py
- src/sardana/macroserver/msmacromanager.py
The macro reserved objects e.g. motion or measurement groups are stopped
when the user stops the macro e.g. Ctrl+C in spock, or directly door's
StopMacro command. This stop is executed in a worker thread which is
comletly desynchronized with the macro execution thread.
Fix it forcing the MacroExecutor to wait for the stopping thread to finish its job
before executing the on_stop or on_abort methods. Also protect macros that
catch the StopException by waiting in the mAPI decorator.
Fixes #8.
@sardana-org/integrators any volunteer to integrate it?
> Properly synchronize stopping of macro and its reserved objects

- doc/source/users/getting_started/installing.rst
- setup.py
Handle install requirements when using `pip`, ~~also conditionally install `ordereddict` when using Python < 2.6~~. 
Apart of that update the documentation to install with `pip` instead of `easy_install`.
> Pip install requirements

- src/sardana/tango/core/util.py
It is not possible to start a new instance of the MacroServer without connecting to a Pool. Fix it.
To test it, assuming that you don't have `test` MacroServer defined in your database, start in the console: 
```
$> MacroServer test --log-level=debug
```
This will offer you to connect to available Pools. Just ignore this offer and press Enter.
Before this was failing with:
```
The device server MacroServer/test is not defined in database. Exiting!
```
Now it starts the server correctly.
> Allow starting MacroServer w/o Pool

- src/sardana/taurus/core/tango/sardana/macroserver.py
This issue was originally reported in Taurus:
https://github.com/taurus-org/taurus/issues/79 but it appeared to be
a bug in Sardana. Fix it by respecting the tango database when creating
PyTango.Group object.
> Fix expconf when using taurus --tango-host option

- src/sardana/tango/macroserver/MacroServer.py
- src/sardana/tango/macroserver/test/base.py
The previous woraround does not cover all the possible cases,
after executing some macros (e.g. ct) the MacrpoServer still
not exit smoothly after Ctrl+C
Force cleanUp for all registered taurus attributes.
Fix #494.
> Apply an agresive workaround for #494

- src/sardana/pool/poolacquisition.py
There is a bug in the acquisition process that affects pseudo counters not
included in the measurement group. The first time the acquisition takes place
this pseudo counters are notified about the value buffer events of the
physical element and their value buffers are filled with the calculation
results. The problem appears in the subsequent acquisitions cause the
pseudo counters buffers are not cleared.
Fix it by clearing the pseudo counters buffers at the beginning of each
acquisition.
**Note for the reviewers/integrator**: To reproduce the problem I have used a setup with:
* 11 dummy counters: ct01, ct02, ..., ct11
* 10 IoverI0 pseudo counters: pc01 = ct02/ct01, pc02 = ct03/ct01, ..., pc10 = ct11/ct01
* measurement group containing just the 11 dummy counters
The first ct macro …
> Fix bug with pseudo counters not involved in acquisition

- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/taurus/core/tango/sardana/macroserver.py
PreScanSnaphot with scalar values does not work:
```
File "/storagebls/beamlines/bl22/controls/devel/SardanaSep6/sardana/src/sardana/macroserver/msmacromanager.py", line 1277, in runMacro
for step in macro_obj.exec_():
File "/storagebls/beamlines/bl22/controls/devel/SardanaSep6/sardana/src/sardana/macroserver/macro.py", line 2276, in exec_
for i in it:
File "/homelocal/sicilia/lib/python/site-packages/sardana/macroserver/macros/scan.py", line 251, in run
for step in self._gScan.step_scan():
File "/storagebls/beamlines/bl22/controls/devel/SardanaSep6/sardana/src/sardana/macroserver/scan/gscan.py", line 884, in step_scan
self.start()
File "/storagebls/beamlines/bl22/controls/devel/SardanaSep6/sardana/src/sardana/macroserver/scan/gscan.py", line 839, in start
self.data.start()
File …
```
> PreScanSnapshot does not work with the default H5 recorder

- src/sardana/macroserver/recorders/h5storage.py
During the Jul17 release tests, it has been discovered that the new H5 recorder has problems with the old versions of dependencies. These are python 2.6 and some specific versions of h5py and libhdf5.
The python 2.6 backwards compatibility is already provided in this PR.
The h5py 1.3.0 and libhdf5 1.8.1 issue is:
```
SardanaTP.W002 DEBUG    2017-08-02 08:21:27,921 Door/demo2/1: Traceback (most recent call last):                                                                               
File "/homelocal/sicilia/tmp/local/lib64/python2.6/site-packages/sardana-2.3.0-py2.6.egg/sardana/macroserver/msmacromanager.py", line 1277, in runMacro                      
for step in macro_obj.exec_(): …
```
> [WIP] NXscanH5_FileRecorder backwards compatibility with old libraries

- src/sardana/sardanautils.py
There was a TypeError that had a malformed message due to a missing percent sign that should fill the error message with types.
> Add missing percent sign to an error message

- src/sardana/sardanacustomsettings.py
- src/sardana/spock/ipython_00_10/genutils.py
- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
Allow choosing the number of Taurus relaged deprecation warnings
that will be displayed, thanks to a sardanacustomsettings
new variable.
Allow to hide Taurus related deprecation warnings if the
variable is set to 0.
> Allow to hide Taurus related deprecation warnings

- doc/source/users/scan.rst
- src/sardana/macroserver/scan/gscan.py
- src/sardana/macroserver/scan/scandata.py
The very first points in the continuous acquisition e.g. ascanct may be omitted, for example, if the motor updates to the software synchronizer were not precise/fast enough. In this case the zero order interpolation does not help if we want to get rid of the NaN values.
Introduce a new concept: extrapolation to avoid NaN in the very first points of measurements. Also, add ApplyExtrapolation environment variable to control this feature.
> Add optional extrapolation of missing records in continuous scans

- src/sardana/spock/spockms.py
Ctrl+C, or stopping a macro, exits immediatelly, not waiting until the
stopping has finished. Make the stopping wait until the door state has
changed to different than Running.
> Fix bug-34: Make spock wait until Ctrl+C is finished

- src/sardana/tango/macroserver/Door.py
It is  a workaround for a bug in PyTango (https://github.com/tango-controls/pytango/issues/147), i.e. temporary solution for issue #447
> add caching for RecordData attribute issue #447

- src/sardana/tango/core/util.py
When creating a MacroServer, the Pool names are presented in
order to allow the user to choose one of them.
Present them by alphabetical order.
> Present Pool Servers by alphabetical order

- src/sardana/pool/poolsynchronization.py
Software synchronizer is started as the last one in the synchronization
action when the hardware TriggerGate elements are already working. This is
not a problem if the hardware TriggetGate elements work in the position
domain but if they work in the time domain they may start triggering too
fast with respect to the motor's move - the motors are started to move
by the GScan when the MeasurementGroup Start has finsihed. Make the hardware
TriggerGate elements start as the last ones in the synchronization action
what aslo means the last ones in the MeasurementGroup Start command. This
change does not affect the software synchronization which works in the
position domain.
> Start hardware TriggerGates as last ones

- src/sardana/pool/poolacquisition.py
Software synchronized acquisition receives wrong number of repetitions
(the global one, that should be passed only to the hardware synchronized 
acquisition). Fix it by setting 1 as number of repetitions - single software
synchronized acquisitions will be repeated while the software synchronizer
triggers them.
> Fix repetitions for software acquisition

- src/sardana/macroserver/scan/gscan.py
Final position is wrongly check against its limits. Fix it.
Also fix the motor name extraction in order to correctly format the error message.
> Fix validating motor positions with limits in ascanct & co.

- src/sardana/macroserver/scan/gscan.py
Too many timestamps are generated. The initial delay already indicates
timestamp of the first point so the loop over repeats must iterate
one time less.  Fix it.
> Fix bug in generate timestamps (ascanct & co.)

- src/sardana/spock/ipython_00_10/genutils.py
- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
Present the door list in an ordered fashion
When creating a new spock profile, present the door list
in an ordered way. Done for ipython >= 1.0.
- First: the doors containing aliases are presented in
alphabetical order.
- Second: the doors that does not contain an alias are presented
at the end of the list also ordered alphabetically.
> Issue221: Present the door list in an ordered fashion

- src/sardana/pool/poolacquisition.py
Improve the start_action method, solve problems on manage mutable
objects enabling/disabling measurement group channels.
This patch solves conflicts on save the measurement Group configurations when it has disabled channels.
This Pull Request is related with [PR-607](https://github.com/sardana-org/sardana/pull/607)
> Fix use of mutable channels object

- src/sardana/macroserver/scan/gscan.py
Currently, StopException is not raised again to the higher layers. Due to that
the GScan.step_scan method is not able to determine if the scan was stopped
by the user or not. Furthermore, if the scan was run inside of another macro
the StopException is not propagated to the wrapper macro. Change it and
re-raise the StopException
Apart of that, after ScanException the on_waypoints_end method is not called. This
method does the necessary cleanup. Call it.
> Improve exception handing in continuous scans

- src/sardana/taurus/qt/qtgui/extra_pool/poolchannel.py
PoolChannel shows "dev_alias" as label instead of the device alias
with Taurus4
Fix #617
> PoolChannel shows "dev_alias" as label

- src/sardana/macroserver/macros/test/test_expert.py
MeasTest.test_meas fails on travis due to issue #57. Execution of
the testsuite in the same docker container that uses travis locally
does not fail. Skip it until we fix this issue.
> Skip MeasTest.test_meas until #57 is fixed

- src/sardana/pool/poolacquisition.py
Intermediate events of counters were temporarily removed with the acceptance
of SEP6. Introduce them again for software synchronized acquisition.
> Re-introduce intermediate event of counters

- src/sardana/macroserver/scan/gscan.py
taurus-org/taurus#488 introduced FQDN in model names. The channel's
column description is composed from the full_name that is composed in
the Pool and transferred with the measurement group configuration and it
does not contain the FQDN. Adapt CAcquisition.buffer_changed callback
to be compatible both with Taurus3 and Taurus4.
> Adapt continuous scans to FQDN in Taurus 4 model names

- src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
Dummy counters involved in an acquisition that was aborted always
returns the value corresponing to the integration time even
if the abort happend earlier. Fix it and always return the real value
of the counter. This has a side effect on the noramlly finished
acquisition which from now on does not show the round number.
If you don't like the side effect we should work on how to return the round
number in case of normal end of the acquisition.
> Fix dummy counter value after abort

- src/sardana/macroserver/scan/gscan.py
Moveables can not contain scheme in their names cause the internal Pool
registers do not use schemes. Strip scheme from the moveables full names
so they are understandable by the Pool.
> Fix continuous scans when used with Taurus4

- src/sardana/macroserver/scan/test/test_recorddata.py
The test uses NXscan_FileRecorder that will fail if nxs is not
installed.
Skip the tests.
> Skip recorddata test is nxs is not installed

- src/sardana/macroserver/macros/examples/motion.py
Move of a motor may not started if, for example, it was requested to
move out of the limits. In this case does not wait for the movement to
finish.
> Macro move_async may fail if movement could not be started

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
The sequencer allows to import text files with macro sequences.
If a macro from the sequence in the text file contains an error,
report the line where this error is found.
> Report error number when loading sequence from txt

- src/sardana/macroserver/scan/gscan.py
- src/sardana/taurus/core/tango/sardana/pool.py
Hardware problems (missed triggers or positioning problems) could leave the
acquisition waiting infinitely. Add a timeout/watchdog mechanism that will
stop the measurement group if the estimated acquisition time elapses and
the measurement group does not finish. Add an extra time (15 s) to be
sure that the acquisition will not finish. Fix #136.
The extra time is hardcoded now. But I imagine we will make it configurable in the future when we get experience with this kind of problems.
> Implement timeout/watchdog in continuous scans (issue-136)

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Setting of label config in PMTV has no effect - the widget works exactly the same
if the line is removed. This applies both to Taurus3 and Taurus4.
> Removed uselles setting of label config in PMTV

- src/sardana/tango/macroserver/Door.py
The Elements attributes are foreseen for exposing all elements
to the clients in form of encoded stream of data
e.g. Pool's elements, MacroServer elements.
Eliminate ElementList Door attribute since it is accessible from
the MacroServer.
> Eliminate ElementList Door attribute

- src/sardana/macroserver/macros/lists.py
- src/sardana/macroserver/macros/standard.py
It is not well defined how to use default values of repeat parameters.
Now there exist two possibilities of definition: either on the repeat
parameter level or on the member level. For repeat parameters of only
one member defining the default value on the member level is not enough
cause the execution of the macro with the Macro.execMacro call fails.
The failure is related with the ParamDecoder.decodeRepeat implementation.
Duplicating the default value on the repeat parameter level workarounds
this. Apply this workaround until #427 is properly fixed.
> Workaround for bug #427 - default values of repeat parameters

- src/sardana/macroserver/macro.py
Setting hooks property only partially cleans the internal data structures
containing information about hooks. Apart of cleaning the _hooks structure
also clean the _hookHintsDict
> Properly clean hooks information when setting hooks property

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
Macrobutton text is set to the Door name if MacroServer
is stopped. This is a not desired behavior, and the text
of the macrobutton should remain the same.
Reimplement macrobutton handleEvent in order to avoid text
setting when MacroServer is down, or when macroserver is
reconnected.
> Reimplement macrobutton handleEvent

- src/sardana/taurus/core/tango/sardana/macroserver.py
Taurus3 used to return None for the getState query when the device server
was down. Taurus4 raises exceptions which are currently not handled.
In this case provide the same behavior as Taurus3 - assign None to the old
state.
This exceptions appear in spock or any macroserver related widget e.g. macrobutton.
> Avoid exceptions in spock and widgets when MS is down

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
Add text Run/Abort before the name of the macro in macrobutton,
in order to better descrive its behavior.
> Add text Run/Abort in macrobutton

- .flake8
PR #635 introduced flake8 configuration file. This automatically overidden the
default configuration of flake8. Recover it back by explicitelly ignoring some errors.
> Recover default configuration of flake8

- .travis.yml
Travis builds started to fail from the Ubuntu Trusty roll-out
from 12.12.2017. Use the old image. More info in:
https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
Another PR will be open to investigate where exactly is the problem.
From the logs we can see that neither Pool nor MacroServer can be started on docker:
```
$ if [ $TEST == "testsuite" ]; then docker exec sardana-test supervisorctl start Pool; fi
Pool: ERROR (abnormal termination)
$ if [ $TEST == "testsuite" ]; then docker exec sardana-test supervisorctl start MacroServer; fi
MacroServer: ERROR (abnormal termination)
```
> Use old Ubuntu image for travis-ci to fix build errors

- src/sardana/tango/core/util.py
The following error is raised when trying to create a MacroServer instance and the database does not contain any Pools:
```
root@taurus-test:/sardana# ~/.local/bin/MacroServer test
test does not exist. Do you wish to create a new one (Y/n) ? Y
Available Pools:
Traceback (most recent call last):
File "/root/.local/bin/MacroServer", line 11, in <module>
load_entry_point('sardana', 'console_scripts', 'MacroServer')()
File "/sardana/src/sardana/tango/macroserver/__init__.py", line 68, in main
run(start_time=datetime.datetime.now())
File "/sardana/src/sardana/tango/macroserver/__init__.py", line 61, in main_macroserver
name=SERVER_NAME)
File "/sardana/src/sardana/tango/core/util.py", line 1058, in run
log_messages.extend(prepare_server(args, tango_args))
File …
```
> Fix MacroServer creation when there are no Pools in database

- src/sardana/macroserver/macros/scan.py
The total_scan_intervals key of the ScanDataEnvironment, does not have value for all aNscan types.
> Missing  value of the total_scan_intervals. 

- src/sardana/tango/core/util.py
Add two tiny improvements:
- Exit smoothly when user aborted MacroServer creation, using the Ctrl+c on the Pool selection
- Abort server startup process when it is known that its instance won't exist in the DB so it won't be able to
startup
> Improvements when server startup process is aborted

- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolmeasurementgroup.py
The measurement group (MG) does not work, if the controller of the disabled channel  is offline. IMHO this is a bug, because if the channels are disabled the state of the controller is not matter, and it should not affect the working of the other channels. 
We found this problem because we use one MG with all channels of the beamline (4 detectors). The user changes the experiment type by enabling/disabling the channels. If the experiment type is not require one detector, it could be off, in this case, the controller of this detector will be offline, because it can not connect to the hardware.
> Disabled channels and offline controllers

- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/macroserver/recorders/storage.py
The scientists have reported a delay between acquisition and the data available in SPEC file. The data is saved on folder which are mounted on NFS. The Pool and the MacroServer are running on a industrial PC and the spock and PyMCA on a workstation.  
PyMca refresh button the points data of the file is not updated correctly while the scan is writing the data. if we  run a 'watch tail -1 scanfile.dat' on the industrial PC, we can see how the scan file is written at each scan point.
Initially we tried to replicate the problem with bash:
```
while true; do date && sleep 1 ; done >file.txt
```
...but this worked fine (delay <3 seconds). We could do "tail -f file.txt" from a separate PC and it was refreshing properly. So we figured the problem was something that could be seen from the python …
> Force the writing of the file on the disk.

- src/sardana/macroserver/macros/scan.py
The 'getData' method of a aNscan Macro does not return the data, raising the exception "Macro XXX does not produce any data" because the Macro class is returning the value of self._data.
In a aNscan macro the data is available in data @property -> self.data, this PR fix the problem on execute the 'getData' method returning the data.
> Fix getData with aNscan macros

- src/sardana/taurus/core/tango/sardana/pool.py
An experimental channels from an offline controller does not export its
attributes. Then, it is not possible to obtain the Value attribute
configuration and an empty AttributeInfoEx is created for it. Its default
data_type is set to DevVoid. Handle this case and consider the
TangoChannelInfo with an unknown data_type. This avoids errors.
A change was proposed to Taurus that would avoid this PR: https://github.com/taurus-org/taurus/pull/666.
> Avoid errors when acquiring with offline controller

- src/sardana/pool/poolsynchronization.py
- src/sardana/pool/test/fake.py
- src/sardana/util/funcgenerator.py
- src/sardana/util/test/test_funcgenerator.py
Add protection for software synchronizer for cases when the
motor controller ReadOne method fails. Log the errors in
the Pool logs, and continue the scan, given that may be
just a temporary unavailability of the motor's position.
> Add protection for SW synchronizer

- CHANGELOG.md
- src/sardana/macroserver/macro.py
- src/sardana/macroserver/macros/env.py
- src/sardana/macroserver/msmacromanager.py
This PR is for development of the GeneralHooks feature as requested in #200.
TODOs:
Open questions:
For testing I use this https://github.com/reszelaz/generalHooks. Ideally this should be converted into tests...
Fixes #200
> [WIP] Add support to GeneralHooks (#200)

- src/sardana/macroserver/scan/gscan.py
Move the setting of _index_offset attribute before the post-configuration hook, to allow its changing if the nr_point changes between waypoints.
> Move index offset setting

- src/sardana/tango/core/util.py
- src/sardana/tango/macroserver/MacroServer.py
- src/sardana/tango/pool/Pool.py
The main purpose of this PR is to allow the use of [elastic stack](https://www.elastic.co/) for:
* logging analysis i.e. merging logs of Pool and MacroServer in a time ordered events
* extracting metrics from the logs about the system performace e.g. server restarts, macro errors, etc.
This PR adds a logging handler for pushing log events to the logstash. An alternative solution, well actually the recommended by elastic one, would be to use Beats. However Beats require a modern OS to run and we at ALBA are stuck with openSUSE 11.1 which does not support it. So, it adds an optional dependency to the [logstash](https://pypi.python.org/pypi/python-logstash/0.4.6) module.
Configuration is done via Tango properties (other soltutions e.g. sardanacustomsettings were also evaluated). Properties …
> Logstash log handler

- doc/source/devel/howto_controllers/howto_motorcontroller.rst
The Read and State sequences executes the hardware queries algorithms
per controller concurrently. This is the desired behavior.
Correct the documentation so it reflects the implementation.
> Correct documentation to reflect the implementation

- src/sardana/pool/poolmotorgroup.py
- src/sardana/taurus/core/tango/sardana/pool.py
Fix for bug #259 (SF#414).
Before starting group movement I check the limits for each motor and raise an exception if requested position is outside.
> Check motors limits before motor group movement

- src/sardana/tango/macroserver/Door.py
This is a workaround for #693 that we will apply for Jan18 release instead of integrating #695 which has a side effect (probably due to a bug in Tango).
> Workaround issue 693 - avoid deadlocks when aborting a macro

- src/sardana/taurus/core/tango/sardana/macroserver.py
- src/sardana/taurus/core/tango/sardana/motion.py
- src/sardana/taurus/core/tango/sardana/pool.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
Sardana extensions wrongly expect attributes to be
alive even if no one keeps a ref to them.
After https://github.com/taurus-org/taurus/pull/692, this is no longer the case, and
sardana extensions must keep their own references.
> Add internal reference to keep subscribed attrs alive

- src/sardana/spock/ipython_01_00/genutils.py
Using Spock with a bright background terminal themes commands are not visible
It seems related with an IPython V5  bug https://github.com/ipython/ipython/pull/9655
Change spock colors to  'Neutral' for IPython >= V5
Fix #706
> spock commands not visible with bright background

- src/sardana/macroserver/recorders/h5storage.py
os.path.join is failing in windows for this case.
This was making the scans to abort when a h5 files was indicated as ScanFile.
Use the concatenation with plus signs instead.
> Do not use os.path.join

- src/sardana/macroserver/macroserver.py
Since `edmac` can only work with paths without trailing slash, this modification will always strip trailing slashes (or other path separators, it uses `os.sep` for this) upon adding new macro path.
I wanted to check if `edctrlcls` and `edctrllib` also work that way, but encountered these problems:
```
Door_demo2_1 [2]: edctrlcls EpochZeroDController
An error occurred while running Macro 'edctrlcls(EpochZeroDController) -> 750e8aa2-2135-11e8-ba32-0800277db4d3':
'ControllerClass' object has no attribute 'file'
Door_demo2_1 [9]: edctrllib /home/daneos/controllers/EpochZeroDController.py
An error occurred while running Macro 'edctrllib(/home/daneos/controllers/EpochZeroDController.py) -> b375e2b2-2136-11e8-ba32-0800277db4d3':
'MacroServer' object has no attribute 'getPool'
```
> Strip trailing slash from macro path

- src/sardana/macroserver/scan/test/test_recorddata.py
nxs module is not available in Debian 9.
Postpone nxs import to setUp and skip the test if nxs is not available.
> Skip ScanData tests if nxs is not available

- .travis.yml
Use two different docker images for CI:
- Debian 8 together with Taurus 3
- Debian 9 together with Taurus 4
> Add CI for Debian 9 and Taurus 4

- src/sardana/tango/pool/test/test_measurementgroup.py
The problem with tests on openSUSE 11.1 (Taurus 3) revealed during the last release Jan18 and reported in https://github.com/sardana-org/sardana/pull/711#issuecomment-372592667 has to do with PQDN/FQDN compatibility. The good thing is that it was affecting only the tests. Only the systems with TANGO_HOST set to PQDN were affected. 
This PR fixes this problem, so now all the tests passes.
> Fix test when TANGO_HOST with PQDN is used (Taurus 3) - revealed during Jan18 release

- src/sardana/macroserver/recorders/storage.py
on Windows the default EOL is CR LF also for the SPEC files but this is not readable for programs like PyMCA. Force the EOL to only LF using io package instead of python's default io lib
> change EOL to always \n in SPEC_FileRecorder

- doc/source/users/getting_started/installing.rst
Documentation on how to work directly from a git checkout is outdated.
Document the "pip -e" recipe (text borrowed from Taurus docs)
> (doc) Update docs about installing in editable mode

- src/sardana/macroserver/msmacromanager.py
#655 fixed hooks property however the MacroExecutor
was still using it in the wrong way. Properly use the appendHook method
to append hooks instead of setting the whole list of hooks.
Reported in #744.
> Fix appending of hooks from sequence XML

- src/sardana/macroserver/recorders/storage.py
when using xrayutilities one cannot read the spec file written by Sardana because the "#D" field is not in date time format like "Sun May 17 08:09:19 2015"
This is also the way SPEC is saving the "#D" field
> change epoch from float to formatted date time

- src/sardana/macroserver/macros/env.py
The macro lsgh was listing each hook macro only once, even if it was added several times in the same
positon, but the macro was called so many times as it was added. This PR makes consistent the lsgh with what is happening.
> Correcting lsgh if macro several times in same hook position

- src/sardana/macroserver/scan/gscan.py
As agreen in #711 we need a public access to data_handler object of `GScan`, for example for adding
custom data. Add a read only property.
Whenever integrated we should change the examples accessing to it via `_data_handler` protected member e.g. `ascan_with_addcustomdata` macro.
> Add public access to data_handler in GScan

- src/sardana/util/funcgenerator.py
Allow function generation when group has 1 repeat only
When group has one repeat only the generation of active and passive events
is much simpler. It requires only Initial and Active parameters and Total
parameter is not needed. Implement different algorithm of generation of
events when repeats is 1.
Any @sardana-org/integrators could take a look on this, please?
> Allow function generation when group has 1 repeat only

- CHANGELOG.md
- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
PoolMotorSlim is an old widget for controlling motors that was
developed before TaurusForm and TaurusValues existed. PoolMotorTV
is the modern alternative to PoolMotorSlim. It was discussed several
times that PoolMotorSlim should be deprecated, for example in #163, so
deprecate it now.
> Deprecate PoolMotorSlim in favor of PoolMotorTV

- src/sardana/macroserver/scan/gscan.py
- src/sardana/macroserver/scan/scandata.py
- src/sardana/macroserver/scan/test/test_recorddata.py
In one of our setups using continuous scans we found that sporadically the hardware synchronized channels were loosing data but the scan was correctly finishing. With the involved hardware this is not possible and was pointing to a bug in software.
After some debugging we found a wrong implementation on handling the value buffer (data) events on the MacroServer side - see 92dc5c6 comment for more detail.
This issue can be reproduced with the following simplified snippet, when while executing one would see "i is different than idx" messages:
```python
import time
import threading
from sardana.sardanathreadpool import get_thread_pool
pool = get_thread_pool()
lock = threadingLock()
idx = 0
def job(i):
global idx
with lock:
print "Entering critical section of job %d" % i
if i != idx:
print "i …
```
> Continuous scans may loose data

- src/sardana/macroserver/recorders/h5storage.py
as pointed out in #720 in `h5storage.py` the `os.path.join` has to be replaced to always use "/" as path separators for NeXuS paths.
In order to do so, the `posixpath` module is used which has the exact same interaface as the `os.path` module but uses always UNIX-style path-separators, see https://docs.python.org/2/library/os.path.html
> Fix nexus path windows

- src/sardana/macroserver/macros/standard.py
allow pre-acq and post acq-hooks for ct macro.
Add integ_time as property of ct macro class to make it accessible from within the hooked macros
> add hooks to ct macro

- doc/source/devel/guide_coding.rst
This commit removes the old code repository reference from the coding
guide.
> Remove the old code repositories reference

- src/sardana/taurus/core/tango/sardana/pool.py
Sardana element identifiers were changed to FQDN URIs during the Jan18
release. Prior to that a big code base was adapted to be compatible both
with Taurus3 and Taurus4. Remove this code cause with Taurus 4 it is no
more necessary.
@sardana-org/integrators can you take a look on this?
> Clean code from Taurus3/Taurus4 FQDN compat.

- src/sardana/macroserver/macros/scan.py
In the Nscans the column_desc in the data record contains min_value and max_value with the scan limits. We need this information also for the mesh scan. This PR implement it.
> Adding min_value and max_value to column_desc for mesh scans

- src/sardana/taurus/core/tango/sardana/pool.py
This solves #57 and redistribute to the correct classes the `getPoolData` and `getPoolObj` fallback implementation. More details in the comments of the commits and in the code itself.
This requires #863.
> Fix Pool element taurus extensions when Pool object ref was not filled (Fix Issue 57)

- src/sardana/pool/poolmetacontroller.py
Some old controllers define its description property using a string
'Description' instead of using the
'sardana.pool.controller.Description' constant.
A recent modification were base on this constant and cause an
exception during the loading of the controllers.
Add back. comp. raising a deprecation warning.
> Allow back. comp. for defining ctrl. property

- src/sardana/macroserver/scan/gscan.py
`CAcquisition` is creating a new pool of threads everytime it is instantiated.
These threads requires disposal, othewise the OS will complain that it can
not create more threads.
Add a method to join the pool of threads and call it from continuous scan
and timescan.
Can be tested by counting the number of threads in a process using:
`$> ps huH p <macroserver-pid> | wc -l`
Before it was increasing after every execution of the continuous scan, now it stays contant.
Can @sardana-org/integrators take look on this, please.
> Join pool of threads in cont scan

- src/sardana/macroserver/msmacromanager.py
- src/sardana/sardanacustomsettings.py
The output of the implemented  spock logging feature was not accepted by some users.
A filter is added for adapting the output to the user requests.
> Adding filter to spock logging filehandler

- src/sardana/macroserver/scan/gscan.py
The generic intervals estimation is used on the mesh and dmesh scans. The method returns the numbers of point and not the number of intervals. On the other scans: aNscan, aNscanct, meshct, etc. the value returned corresponds to the intervals and not to the scan points.
> Fix generic intervals estimation

- src/sardana/macroserver/macros/scan.py
- src/sardana/macroserver/scan/gscan.py
Expose allowsHooks hint of timescan macro.
Implement pre-acq and post-acq hooks in TScan class.
@sardana-org/integrators can you take a look, please?
> Allows hooks in timescan

- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
Enabling pylab support in IPython also exports all numpy and pylab
symbols into the namespace. Some sardana macros may collide with these
symbols e.g. repeat or where. This forces the macro execution with the
"%" symbol - explicitly indicating execution of a magic command.
Disable the export of these symbols into the spock's namespace for
IPython >= 0.11.
I was not able to find such configuration for IPython 0.10 but I think that we at Alba are the only ones using this version. Just in case someone wants to look for it I post a link to the [IPython 0.10.2 documentation](https://ipython.org/ipython-doc/rel-0.10.2/html/index.html).
This improves user experience in #892 and #890.
I've tested it on IPython 0.13.2 and IPython 5.1.0.
@sardana-org/integrators could you please take a look on it?
> Remove numpy and pylab from spock namespace

- src/sardana/macroserver/basetypes.py
- src/sardana/spock/ipython_00_10/genutils.py
- src/sardana/spock/ipython_00_11/genutils.py
- src/sardana/spock/ipython_01_00/genutils.py
The boolean type is not protected and it does not allow to use 0/1 as values. 
Macro to test it:
```python
class test_boolean(Macro):
param_def = [['val', Type.Boolean, None, 'value']]
def run(self, value):
self.info(value)
````
> Fix incorrect conversion to boolean

- src/sardana/macroserver/macros/discrete.py
- src/sardana/macroserver/macros/discretepm.py
- src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py
Provide a more pythonic interface to the discrete pseudo motor
configuration.
The new configuration attribute encapsulates the values
from the label and calibration attributes as a dictionary.
The dictionary keys are extracted from the labels attribute.
and each dictionary entry is also a dictionary with four keys:
a `pos` key corresponding to the label enumerated position
integer value and three float values corresponding to the
calibration values and named as `min`, `set`, and `max`.
Three different macros are proposed to manage this configuration:
`def_dpm_pos`, `udef_dpm_pos` and `prdef_dpm` to add/remove a point
to the configuration and to print the configuration on screen.
> Add configuration attribute to DiscretePseudoMotorController

- src/sardana/macroserver/scan/gscan.py
In some cases the ideal velocity cannot be reached and the calculations of the scan are done with a ideal velocity instead the real velocity.
With this PR, the calculations are done with the real velocity, also, the if the real velocity is greater than the ideal velocity, it will try to adjust the real velocity equal or lower than the ideal vel, never greater.
> Calculation with real_vel instead ideal_vel

- src/sardana/pool/poolmeasurementgroup.py
We use one measurement group with all the channels of the beamline, and according to the experiment we enable/disable the channels. If there is a controller with all the channels disabled, the measurement group  start method, will load the configuration into the controller anyway, this will take an unnecessary amount of time. In the worst case, the starting of the measurement group can trigger a timeout exception.
> Skip configuration loading for ctrls disabled.

- src/sardana/spock/ipython_01_00/genutils.py
When spock is used with Taurus4 store in the spock configuration file
Door and MacroServer FQDN URI references.
This is resting part of #668.
@sardana-org/integrators can you take a look? I've tested it with Taurus 4 but now with Taurus 3.
Note this does not upgrade the already exiting configuration file. I would not block the release for that cause there is a backwards compatibility layer so old configuration files basically works.. If at some point we want to upgrade them we can add it a posteriori.
Also I've not implemented it for IPython < 1.0. It is not probable that someone will use Taurus 4 together with such version of IPython.
> Store FQDN URI for Door and MacroServer in spock conf file

- src/sardana/macroserver/macros/standard.py
According to the discussion in #802, the syntax is implemented as:
Door> repeat 100 "ascan mot01 0 10 10 0.1" "ct 10" "dscan mot02 -20 20 6 0.2"
> Extend repeat macro to run it easily from spock

- src/sardana/pool/poolpseudocounter.py
Let's consider the folowing example. A pseudo coutner is based on two
counters. If counter#1 reported value of index 1 and 3 in separate
chunks and then counter#2 reported values 1, 2 and 3 in the same chunk,
the pseudo counter won't calculate the index 3. This is because the
LateValueException is returning from the on_change callback, ignoring
all the following indexes. Fix it by continuing the loop and just
skipping calculation for late values.
@sardana-org/integrators this is ready to be reviewed
> Fix pseudo counters in continuous acquisition.

- src/sardana/taurus/core/tango/sardana/macroserver.py
This fixes #717 and fixes #725.
@sardana-org/integrators can you take a look please
> Increase timeout for door state events in BaseDoor

- src/sardana/macroserver/scan/gscan.py
Add a check point in order to avoid filling missing records when
timescan is aborted by the user. Fix #869. @cmft can you check that?
> Do not fill missing records if timescan is stopped

- src/sardana/macroserver/macros/scan.py
Continuous scans e.g. `ascanct`, `dscanct` or `meshct` does not allow to attach all hook places even if in the code they are implemented. Fix it by correctly defining `allowHook` hint. Do it in newly created base clases for these macros in order to avoid duplication of code.
> Correct continuous scan hooks

- src/sardana/macroserver/macros/hkl.py
This is a trivial PR, it corrects a typo.
> Typo in phi name

- src/sardana/sardanameta.py
If a macro module does not have '__doc__' defined
'sar_info' macro reports as description "MACRO in error"
that is not the case.
Fix #944
> Fix sar_info macro reports a wrong description

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
Avoid exception raising during the macro typing on the macroexecutor widget. It resolves #941
> Add protection on parameter info reading

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
Pull Request to solve the [issue 931](https://github.com/sardana-org/sardana/issues/931) (Macrobutton should try to stop macro instead of direct aborting #931)
> MacroButton Stop macro instead direct Aborting

- doc/source/devel/howto_macros/macros_general.rst
- src/sardana/macroserver/macros/test/test_gh.py
- src/sardana/macroserver/macros/test/test_macro.py
- src/sardana/macroserver/macros/test/test_scanct.py
- src/sardana/macroserver/msmacromanager.py
- src/sardana/tango/macroserver/test/base.py
#781 made `ParamParser` aware of the parameters definition. General hooks use the `ParamParser`. Adapt geral hooks implementation to pass the parameters definition to the `ParamParser`.
Also add some unit tests.
@sardana-org/integrators it is ready fore review. Thanks!
> Fix general hooks broken by #781

- doc/source/users/configuration/macroserver.rst
This PR complements the MacroServer configuration docs. Eventually, we could add in the future a dedicated chapter for Sardana debugging and a part of this information could be moved there.
@sardana-org/integrators could you please take a look and eventually integrate it? Thansk!
> Document RConsolePort

- doc/source/devel/howto_controllers/howto_controller.rst
- doc/source/devel/howto_controllers/howto_pseudocountercontroller.rst
- doc/source/glossary.rst
- src/sardana/tango/pool/PoolDevice.py
- src/sardana/tango/pool/PseudoCounter.py
This feature was initiated by the #982 discussion. Now it is possible to define pseudo counters which returns a scalar, a spectrum or an image.
I tested it with the following trivial example:
```python
class ROI(PseudoCounterController):
"""A simple pseudo counter which receives an image from a 2D experimental
channel and returns 1D of its first row"""
counter_roles = "2D",
def GetAxisAttributes(self, axis):
axis_attrs = PseudoCounterController.GetAxisAttributes(self, axis)
axis_attrs = dict(axis_attrs)
axis_attrs['Value'][Type] = (float,)
axis_attrs['Value'][MaxDimSize] = (1024,)
return axis_attrs
def Calc(self, axis, counter_values):
i = counter_values[0]
s = i[0]
return s
```
It is very trivial, and assumes image of 1024 x 1024 pixels (for example the one provided by the …
> Allow changes of pseudo counter data format (shape)

- src/sardana/macroserver/scan/gscan.py
Taurus 4 uses quantities as attribute values, range, etc. Sardana for
the moment does not support them, for example it is not possible to
pass macro parameters as quantities. In the continuous scan, when motor
limits are checked, it is better to use the position attribute limit
magnitudes. Fixes #989.
@sardana-org/integrators this is ready for review and eventual integration. Thanks!
> Fix limits protection in ascanct when Taurus 4 is used

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
#882 made expconf incompatible with Qt 4.4 (old style signals). This PR fixes it.
@sardana-org/integrators this is ready for review and eventual integration. Thanks in advance!
I have tested it both on Qt 4.4 and Qt 4.8 and for me both works.
> Fix expconf for Qt 4.4 (signal style compatibility)

- doc/source/users/configuration/macroserver.rst
- doc/source/users/configuration/pool.rst
- src/sardana/tango/core/util.py
- src/sardana/tango/macroserver/MacroServer.py
- src/sardana/tango/pool/Pool.py
This is a follow-up to #699 and an attempt to make Logstash communication asynchronous.
Things changed so far:
* use `python-logstash-async` instead of `python-logstash`
* add `LogstashCacheDbPath` property for both Pool and MacroServer
There is no need to define two Logstash endpoints with tagging (see [example configuration](https://github.com/reszelaz/sardana-elastic/blob/master/logstash/conf.d/sardana.conf)) since the `python-logstash-async` automatically adds `program` field. It's value is taken from the executable name, which in case of single Sardana instance is correctly recognized as `Sardana` and not `Pool`.
The asynchronous library uses caching in local SQLite database, path of which is configured by `LogstashCacheDbPath` property. This caching however causes problems when logs …
> Asynchronous Logstash communication

- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/poolacquisition.py
- src/sardana/taurus/core/tango/sardana/pool.py
[SEP18](https://github.com/sardana-org/sardana/blob/develop/doc/source/sep/SEP18.md) implementation forgot to make a different counts depending whether the scan is deterministic (knowns a priori nr of points and integration times) or non-deterministic (number of points as well as integration times may vary depending on scan generator execution). In the first case a `count_raw` should be called, and in the second case a `count` should be called.
This is something what was agreed by acceptance of SEP18 so if there are no negative voices I will integrate it tomorrow.
> Make effective raw counts for each scan point if this is deterministic (fix SEP18)

- doc/source/devel/api/sardana/pool/pooldefs.rst
- src/sardana/pool/pooldefs.py
SEP18 improved documentation of `AcqSynchType` and `AcqSynch` enumerations. At the same time it broke the `AcqSynchType`. This could be observed when using the expconf and viewing the *Synchronization* column - the following traceback was logged and the values in the columnt were not shown
```
Traceback (most recent call last):
File "/home/zreszela/workspace/sardana/src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py", line 515, in data
return Qt.QVariant(AcqSynchType[synchronization])
TypeError: 'type' object has no attribute '__getitem__'
```
I consider it as the integrators (my) mistake and will integrate it as soon as CI is green. Please comment if you don't agree. Thanks!
> Fix AcqSynchType broken in SEP18

- src/sardana/pool/poolmeasurementgroup.py
This PR fixes measurement group configuration broken with SEP18.
It simply comes back to the solution where the following channel's default configurations: `data_type`, `data_units`, `nexus_path` and `shape` were obtained on the client side (Taurus extension) if not explicitelly set by the user.
An alternative to that could be to generate them on the server side (this is what SEP18 left as a TODO) at the measurement group creation time. For example the `data_type` together with the `shape` could be taken from the controller's axis attribute's definition. The resting two: `nexus_path` and `data_units` could be simply set to empty string.
I have done a proof-of-concept of that and paste it here just in case it is usefull in the future (it may be usefull already in SEP2).
First of all, the …
> Fix measurement group configuration

- src/sardana/pool/poolacquisition.py
- src/sardana/sardanabuffer.py
Physical elements of the pseudo counters need to clear the buffers before each acquisition. In SEP18 this was moved to the acqusition preparation but needs to be done in the acqusition start. Otherwise
step scans does not works.
This solves the issue reported by @dschick in https://github.com/sardana-org/sardana/issues/1011#issuecomment-453490070 .
Since this was broken in SEP18 I assume it as the integrator's (my) mistake and will integrate it as soon as travis-ci is green.
> Fix PC broken in SEP18 - clear buffers before each acquisition

- src/sardana/macroserver/macros/test/test_scan.py
- src/sardana/taurus/core/tango/sardana/pool.py
This PR fixes a bug introduced in the SEP18. The change is trivial, and since it was the integrators (my) mistake I will merge it as soon as we get green light from travis-ci.
I take a profit of this PR to add a test for the timescan macro and will push it in two steps in order to trigger twice the travis-ci. The first push and commit will add a test which should fail and the second push and commit should solve it.
> Fix timescan (count_continuous method) 

- src/sardana/macroserver/scan/gscan.py
- src/sardana/tango/pool/test/base_sartest.py
- src/sardana/taurus/core/tango/sardana/pool.py
- src/sardana/taurus/core/tango/sardana/test/test_pool.py
This PR adds limit checking for start and final position to `GScan`.
The implementation is similar to #560 and #704.
It's still a WIP, because so far it was only tested for step scans, and it will **not** go through the pseudomotor hierarchy to check limits, it will check only the moveables explicitly passed to the scan.
> Check motor limits before starting the scan

- doc/source/users/taurus/experimentconfiguration.rst
- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
As stated in #961 an access to the auto-update feature of expconf from the graphical interface is missing. Note that it is available when starting expconf in spock (--auto-update).
This PR adds a context menu to the expconf (also fixing some context menu issues of the measurement group tab) with an action to enable/disable auto update. Also a short documentation is added.
The autoupdate feature is saved in the applications settings, so in case of setting it in a TaurusGUI this setting will persist (it will be reapplied on the GUI restart). It is pending to add the same feature when expconf is started from spock.
I tested it both on Qt4 and Qt5 and it worked fine for me and I see it ready for review and eventual integration. I see it quite important to be included in the Debian10 release …
> Add auto-update action (context menu) in expconf widget.

- src/sardana/taurus/core/tango/sardana/macroserver.py
This is a cosmetic change about the way we show to the user problems with loading settings in the macroexecutor. The best is to evaluate it with the following eventual changes in Taurus [taurus-org/taurus#855](https://github.com/taurus-org/taurus/pull/855).
Before:
After:
Hint on checking if the MacroServer is alive or if the macro is loaded was moved to the logging message.
> Improve macroexecutor error msg when loading settings

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Register config property with action's setter/getter so it is correctly
restored from the setting.
> Make auto update action correctly restore its settings

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/parameditors.py
Similarly to work done in commit c653457 remove unnecessary
connections in LineEditParam and CheckBoxParam parameditors.
This work is done by ParamEditorDelegate.
Fixes #1030.
@sardana-org/integrators this is ready for the review and eventual integration.
> Fix macroexecutor lineedit parameter editors

- src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py
Added a filter for _experimentConfigurationChanged_ signals with _environmentChanged_ signals as source.
Only changes to the following environment will raise an '_experimentConfigurationChanged_' QDoor signal:
- '_ActiveMntGrp_'
- '_ScanDir_'
- '_ScanFile_'
- '_DataCompressionRank_'
> Add filter for environmentChanged QDoor signals, only for experiment env config.

- src/sardana/macroserver/macro.py
This is related to #962 and #1013.
On one of the internal meetings at Alba @srgblnch commented that the `Hookable.hooks` property setter could warn about the fact of overriding general hooks. What is your opinion to add it?
I already created a PR for that, the output looks like this:
```
Door_zreszela_1 [12]: defgh ct pre-acq
Defining general hook
ct
Door_zreszela_1 [13]: lsgh
Hook place   Hook(s)
------------ ---------
pre-acq        ct
Door_zreszela_1 [14]: captain_hook 0 10 1
previously set hooks, these may include general hooks, are being overridden now
Starting loop
At step 0
running hook with hints=['pre-acq']
hook execution
At step 1
running hook with hints=['pre-acq']
hook execution
At step 2
running hook with hints=['pre-acq']
hook execution
At step 3
running hook with …
```
> Warn when hooks gets overridden

- src/sardana/pool/poolmeasurementgroup.py
This PR fixes #1017 by adding back-comp for measurement group plotting configurations.
Measurement group plotting configurations created with sardana < 2.4.0 and taurus < 4.3.0 are not compatible after the upgrade. Fix it by using channel's full name URIs (tango scheme + FQDN).
@sardana-org/integrators it is ready to be reviewed, thanks!
@julianofjm, @kklmn your confirmation of the fix would speed up the integration process, thanks!
Do you need a hotfix release for sardana 2.4.0 or 2.5.0? Otherwise, soon we will release Jan19 milestone and the fix will be there anyway.
> Add backwards compatibility for measurement group plot configuration (fixes #1017)

- src/sardana/pool/poolmeasurementgroup.py
This was discovered yesterday on the follow-up meeting when doing a demo.
One can reproduce in `itango` where ct02 is a second axis of the dummy counter/timer controller:
```
In [13]: c = CTExpChannel("ct02")
In [14]: c.integrationtime = 0.1
In [15]: c.start()
In [16]: c.timer = "__self"
PyDs_PythonError: AttributeError: 'PoolController' object has no attribute 'remove_channel'
(For more detailed information type: tango_error)
In [17]: tango_error
Last tango error:
DevFailed[
DevError[
desc = AttributeError: 'PoolController' object has no attribute 'remove_channel'
origin =   File "/home/zreszela/workspace/sardana/src/sardana/tango/pool/PoolDevice.py", line 954, in write_Timer
self.element.timer = timer
File "/home/zreszela/workspace/sardana/src/sardana/pool/poolbasechannel.py", line 364, …
```
> Fix independent acquisition when timer is set to __self

- src/sardana/macroserver/macros/standard.py
- src/sardana/sardanadefs.py
#997 introduced independent acquisition of experimental channels.
This PR allows to count them with `ct` and `uct` macros. Now one can do `ct 0.1 ct01` or `uct 0.4 twod01 `
An alternative solution would be to add a dedicated macro e.g. `cti` to be able to count in a manner similar to the `mv` macros e.g. `cti ct01 0.1` or `ucti twod01 0.4` (`i` from independent). But maybe this may introduce too many macros for similar purposes? What are your preferences?
> Adapt ct and uct to accept timerable channels

- src/sardana/pool/poolbasechannel.py
Measurement preparation (introduced in SEP18) is not executed
in independent acquisition of experimental channels. Do it.
One can test it by adding a dummy `PrepareOne` methodn to a controller, executing the independent acquisition and observing if it was called:
```python
def PrepareOne(self, axis, value, repetitions, latency, nb_starts):
self._log.debug("PrepareOne")
```
@sardana-org/integrators can you take a look please?
> Prepare channel in independent acquisition

- src/sardana/tango/macroserver/test/base.py
@mrosanes discovered this in #1058. @mrosanes could you verify if this works on Windows and still on Linux, plese?
> Remove ms properties file in tests correctly on Windows

- src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py
DynamicPlotManager uses a Taurus property that does not exist in T3
version.
Replace it to use a method instead.
> Fix taurus 3 incompatibility issue

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
ExpDescriptionEditor.onChooseScanDirButtonClicked
has a wrong emit syntax.
Fix it.
> Fix wrong signal emit

- src/sardana/macroserver/macros/test/test_gh.py
Some general hook tests refer just to the configuration macros
and some others also execute the macro to which the general hook
was attached in order to check if it could be executed.
Split the tests in two groups cause the setUp and tearDown should
be different. This avoids problems of deletion of the measurement
group when it was never created.
This fixes:
```
Impossible to delete MeasurementGroup: _test_mg_1
DevFailed[
DevError[
desc = KeyError: "There is no element with name '_test_mg_1'"
origin =   File "/home/zreszela/workspace/sardana/src/sardana/tango/pool/Pool.py", line 920, in DeleteElement
elem = self.pool.get_element(name=name)
File "/home/zreszela/workspace/sardana/src/sardana/sardanacontainer.py", line 144, in get_element
return self.get_element_by_name(name, **kwargs)
File …
```
> Separate GH tests into two classes

- src/sardana/tango/macroserver/test/base.py
To avoid problems in windows, remove the macroserver properties
file, after having stopped the MacroServer DS.
> Remove ms_properties file after stopping MS

- src/sardana/pool/test/base.py
Dummy 2D controller generates an array of zeros (1024x1024) for each
axis, many axes may increase the VM memory consumption of testsuite and
this apparently causes OSError: [Errno 12] Cannot allocate memory on
the os.fork() call. Avoid this by just creating one axis of dummy 2D.
Fixes #1067.
> Avoid memory errors on testsuite execution

- src/sardana/tango/macroserver/test/base.py
Removing macroserver.properties file sometimes is giving problems in Windows; and because of that,  errors in the sardanatestsuite increases a lot.
Add try/except to remove macroserver.properties file.
> Get ms_properties from db properties

- src/sardana/taurus/core/tango/sardana/macroserver.py
Clear the event set before running execution and before
macro stop/abort.
This is solving bugs found in Windows, where the spock prompt was
returned before expected, as events arrived with the same
timestamp, cause of poor time resolution of python on windows.
> clear the event set, before macro commnads

- src/sardana/macroserver/scan/gscan.py
Restore the motor configuration before to run the base class method, because the dNscanct macros goes to the starting position with the scan configuration instead of the backup configuration when it is aborted.
> Change order on the CScan do_restore

- src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
Empty _DataType_ field in expconf is considered as unspecified `data_type` configuration. Pop this configuration key so the _downstream_ software can consider it as unspecified and eventually use default values. Setting it to `None` could be reserved for unknown or erroneous conditions.
Fixes #1070.
@julianofjm could confirm that it fixes your problem? How important is this bug to you? Do you need it in an official release? Or merging into develop would be enough?
> Fix expconf when empty (unspecified) DataType

- src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py
Popups are not showing up at macroexecutor when an exception
is occurring. Commit 2db28769 was introducing this bug.
The current commit fixes it.
> Fix bug on exception popups at macroexecutor

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Proposal of a pull request to modify messages in expconf configuration modification popup, to
improve user experience. Simplified the messages by removing technical concepts as 'Door', etc.
> Modify expconf popup messages

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Allow to apply a configuration that has been kept, in expconf.
As the kept local configuration in expconf can be different than
the server configuration, the button Apply shall be active;
allowing in such a way, to apply the local configuration if
desired.
> Allow applying kept configuration

- src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py
- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
This fixes case when the last measurement group is removed remotely and no pop-up with external
changes appears in expconf. It also clears the measusrement group configuration table when active meas group is deleted.
@sardana-org/integrators can you take a look on this? Thanks!
> Show external changes pop-up in expconf when last measurement group is deleted remotelly

- src/sardana/macroserver/macros/demo.py
- src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
- src/sardana/pool/test/base.py
- src/sardana/tango/pool/test/base_sartest.py
Up to now hardware synchronization modes (trigger/gate/start) of dummy counter/timer works but these types of acquisitions starts already on `StartAll` method call. In case of the continuous scan this makes the acquisitions finish too early - not respecting the acceleration time of the moveable. This can be observed on ![this continuous scan trend of motor position and counter/timer state](https://user-images.githubusercontent.com/6735649/56325294-00da8e00-6172-11e9-9b1f-7945a2fabcd5.png).
This was ascanct of dummy motor (vel: 100, acc = 2, dec = 2, base_rate = 0) from 0 to 10 with 10 intervals and 0.1 second integration time. The measurement group contains just a dummy counter/timer synchronized by a dummy trigger/gate in either of trigger/gate/start synchronization modes.
Different …
> Emulate hardware triggering between dummy elements

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/common.py
The PR https://github.com/taurus-org/taurus/pull/906 in taurus disables
the implicit showing of self.taurusMenu as a context menu.
This affects to MacroExecutionWindow (used by macroexecutor and
macrosequncer) since it relies on this feature to show its context menu.
Explicitly overwrite contextMenuEvent to provide the expected behaviour
in this case.
Note: at the moment of writing,  https://github.com/taurus-org/taurus/pull/906 is still pending integration.
However, this PRshould be harmless even if said taurus PR is not merged.
> Adapt to removal of "taurus popup menu" feature

- src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
Global measurement group synchronizer (even if not a bad idea) is
not used. Remove its random setting (to the last selected synchronizer)
so it does not raise a pop-up with external changes in expconf.
@sardana-org/integrators can you take a look, please?
> Remove setting of global measurement group synchronizer

- src/sardana/macroserver/macros/examples/scans.py
This macro demonstrates how to add an extra scan column with the shifted positions of the motor corresponding to the middle of the space interval.
Be aware that the space interval does not necessarily correspond to the middle of the acquisition interval
(remember about the latency time).
This macro does not export all the ascanct features e.g. hooks, ...
> Add scan macro example with a custom column with motor positions shifted to the middle of interval

- src/sardana/tango/pool/TwoDExpChannel.py
This was discovered when testing SEP2 in: https://github.com/sardana-org/sardana/pull/775#issuecomment-494749686.
Default behavior of 2D controllers, if not overridden, is to return
None as data source. However it is not possible to push Tango events with
DevString type with None as value. Compose the default data source as it
is done in read_DataSource.
> Compose default DataSource value pointing to Value Tango attribute

- .travis.yml
Make Travis deploy to PyPI when a version tag (major.minor.patch) is pushed. It uses an ad-hoc PyPI account (sardana_bot) which is given Maintainer permisions in PyPI. The sardana_bot password is encrypted (using [travis-encrypt](https://pypi.org/project/travis-encrypt/)) with the sardana-org/sardana Travis public key so that Travis can decrypt it for deployment.
> Add auto-deploy to PyPI with Travis

- src/sardana/macroserver/scan/gscan.py
Fixes #1114 which was probably inctroduceb by crossed integration of #963 and #816.
> Fix access to macro weakref in GScan limit check

- src/sardana/pool/controller.py
The implementation raises an exception that
requires override `StartAll` method in most of the cases
by a pass.
In order to not force this override, this commit
changes the current implementation by a pass.
Making the implementation more coherence with the
documentation
> Modify StartAllCT implementation

- src/sardana/tango/core/util.py
Integer mapped to DevLong allows to pass integer numbers of 2^31 - 1.
Change mapping to DevLong64 to allow passing numbers of 2^63-1.
This change does have a slight memory footprint effect on py2 32 bits.
There DevLong is simply int and DevLong64 is long. On py2 64 bits
both are int. On py3, regardless of 32 or 64 bits arch, there are only int,
so there is no effect.
This change does have a slight network footprint effect. Tango read
of DevLong attribute requires 160 bytes frame to be transfered while
DevLong64 attribute requries 168 bytes frame. Tango event (ZMQ) of
DevLong attribute requires 226 bytes frame to be transfered and
DevLong64 requires 230 bytes frame to be transfered.
---
One could also think of parametrizing this in `sardanacustomsettings` or even adding new data type to …
> Change mapping of Integer data type to Tango DevLong64

- src/sardana/taurus/core/tango/sardana/macroserver.py
On Windows `stty` is not available what fallbacks to infinite number of characters per line. In this case the number of lines is fixed and always 1.
This was discovered during Jul19 release tests on Windows.
This bug was introduced by #924. I think it is serious enough to be fixed during the release process.
I confirm it fixes the issue on Windows.
@sardana-org/integrators before integrating please crosscheck that on Linux it sill works.
> Fix spock's output block on windows

- src/sardana/spock/inputhandler.py
- src/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/favouriteseditor.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/historyviewer.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Some signals use `object` in their signatures, but this may be
problematic when object is imported from builtins (futurize module).
To avoid it, use taurus.external.qt.compat.PY_OBJECT
This is related to https://github.com/taurus-org/taurus/pull/890
> Use PY_OBJECT for signal signatures

- src/sardana/macroserver/macros/lists.py
- src/sardana/macroserver/msmacromanager.py
- src/sardana/sardanabase.py
Add API in the server to identify if a macro is overwritten and report
a debug message.
Modify 'lsmac' macro to show if a macro has been overwritten.
Develop #930
> Warn when macros gets overridden

- CONTRIBUTING.md
- doc/source/devel/howto_macros/macros_general.rst
- doc/source/glossary.rst
- doc/source/sphinxext/ipython_console_highlighting.py
- doc/source/sphinxext/spock_console_highlighting.py
- doc/source/users/getting_started/installing.rst
After #1089, sardana only works with python3. The examples in the docs use
"python", "pip", print statement, etc. Change them to use python3 equivalents.
Fixes #1184.
> Adapt docs to python3

- src/sardana/macroserver/msenvmanager.py
Construction of dict from a generator changed in py37 making the _pairwise method failing with "RuntimeError: generator raised StopIteration".
The following code demonstrates that:
```python
In [28]: s = [1, "a", 2, "b", 3, "c"]
In [29]: def pairwise(it):
...:     itnext = iter(it).__next__
...:     while True:
...:         yield itnext(), itnext()
...:         
...:         
In [30]: dict(pairwise(s))
Out[30]: {1: 'a', 2: 'b', 3: 'c'}
```
```python
In [6]: s = [1, 'a', 2, 'b', 3, 'c']
In [7]: def pairwise(it):
...:     itnext = iter(it).__next__
...:     while True:
...:         yield itnext(), itnext()
...:         
...:         
In [8]: dict(pairwise(s))
---------------------------------------------------------------------------
StopIteration                             Traceback (most …
```
> Fix setting of env. vars. in py37

- src/sardana/macroserver/macros/demo.py
- src/sardana/taurus/core/tango/sardana/pool.py
This is useful for TaurusGUI demonstration (instrument panels are automatically populaated with elements).
Also we were doing this step in the release tests manually. Programt this in `sar_demo` and `clear_sar_demo` now.
@sardana-org/integrators can you take a look on this? Thanks!
> Create instruments and associate elements to them in sar_demo

- src/sardana/macroserver/msparameter.py
WrongParam message, for example due to object not found, are showed in spock as unknown sardana exception instead of showing a verbose message. This is due to the fact that spock shows just the high level exception message. Since Py3 we raise exception from lower level exceptions (see 77a7aa91) then
we must also pass the exception message to the high level exception. Do it.
To reproduce one can try to run a `mv` macro on a motor which does not exist.
Before this fix:
```
Door_py3_1 [1]: mv mot09 10
Error: Unknown sardana exception
```
After this fix:
```
Door_py3_1 [1]: mv mot09 10
Error: Moveable with name mot09 does not exist
```
@sardana-org/integrators can you look at this please? Many thanks!
> Fix WrongParam message showed in spock

- doc/source/users/standard_macro_catalog.rst
- src/sardana/macroserver/macros/env.py
For the moment two macros were developed: `lssnap` and `addsnap` macros. Of course the macro names, or anything else, can be changed. These are just suggestions...
Also the lssnap macro could be improved to print output in the table format. 
I would also add a macro to remove an alement from the snapshot.
I conservatively marked it as WIP. If someone wants to continue this development - feel free (I won't have time in the next month, or so). If you consider it can already go to develop branch, I think this is also ok since it adds value and is usable.
Thanks in advance for your feedback!
> Add snapshot configuration macros

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
software-update-available is not accessible when using taurus-org/taurus#1012
via theme (on Debian Buster with KDE). Use directly the icon.
This works correctly on Debian Stretch and Debian Buster (both with KDE).
> Don't use theme icon for "Add to favourites" in macroexecutor

- src/sardana/spock/inputhandler.py
Some PyQt5 versions don't like that QApplication
is created with empty list argument.
This should close #1209.
> Fix #1209: Crash on spock startup on buster

- doc/source/devel/api/sardana/taurus.rst
- doc/source/devel/api/sardana/taurus/core/tango/sardana.rst
- doc/source/devel/api/sardana/taurus/core/tango/sardana/macroserver.rst
- doc/source/devel/api/sardana/taurus/core/tango/sardana/pool.rst
- doc/source/devel/api/sardana/taurus/qt.rst
- doc/source/devel/api/sardana/taurus/qt/qtcore.rst
- doc/source/devel/api/sardana/taurus/qt/qtcore/tango.rst
- doc/source/devel/api/sardana/taurus/qt/qtcore/tango/sardana.rst
- doc/source/devel/api/sardana/taurus/qt/qtcore/tango/sardana/macroserver.rst
- doc/source/devel/api/sardana/taurus/qt/qtcore/tango/sardana/pool.rst
- doc/source/devel/api/sardana/taurus/qt/qtgui.rst
- doc/source/users/faq.rst
- src/sardana/taurus/core/tango/sardana/__init__.py
- src/sardana/taurus/core/tango/sardana/macroserver.py
- src/sardana/taurus/qt/qtcore/tango/sardana/__init__.py
This PR partially solves one of the tasks from the Documentation Camp board:
> We should document API of the taurus extensions methods like: count, move, etc. so it contains explicitly the timeout argument.
Maybe it does not document the methods itself but give a short introduction to the Taurus extensions modules: `sardana.taurus.core.tango.sardana` and `sardana.taurus.qt.qtcore.tango.sardana`.
It also adds to the API documentation the whole part about the Taurus Qt extensions.
Finally it also fixes broken links from FAQ "How to call procedures?", so it fixes #1228.
@sardana-org/integrators could you please take a look on this and eventually integrate? Thanks!
> Improve Taurus extensions API documentation

- doc/source/devel/api/sardana/sardanadefs.rst
This part of the  documentation gives problems when constructing Debian package of sardana documentaion.
These data structures are auto documented with autodata. Since these are very big and complicated strcutures, the documentation is not attractive and readable at all. Remove them from the API documentation and just leave the docstings in the code.
An example of how it looks now:
> Remove INTERFACES and INTERFACES_EXPANDED from sardanadefs documentation

- src/sardana/macroserver/msmacromanager.py
In spock syntax when you use string parameters with white spaces you need
to use quotes. However when you use RunMacro Door's command, you already
pass string parameters as DevVarStringArray separate items. Then it
should not be mandatory to use quotes for string parameters with white spaces.
Fix it by quoting this parameter values when necessary.
One can test it with this kind of macro:
```python
class str_par(Macro):
param_def = [["value", Type.String, None, "string parameter"]]
def run(self, value):
self.print(value)
```
Before, executing RunMacro command with ["str_par", "Hola, que tal?"] was giving error. With this PR it works. 
@sardana-org/integrators could you take a look on it? Many thanks!
> Fix RunMacro execution with string parameters without extra quotes

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Some widgets add listeners to volatil Taurus attributes.
This cause that the widgets seems to be frozen.
Fix them, keeping local references.
> PM widgets do not keep attribute references

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
PMTV is not ready to work with quantities and #1206 while removing
deprecation warnings introduced the use of quantities. Extract quantity
magnitude so the widget works as previously.
> Use magnitude of attributes values in PMTV

- src/sardana/pool/poolmeasurementgroup.py
MeasurementGroup's configurations created with Taurus3 were supposed to be backwards compatible when migrating to Taurus 4. Now this is broken (most probably after accepting SEP18). Fix it by converting timer and monitor configurations to use full URIs (scheme + FQDN in authority).
We discovered this issue while migrating BL04 at ALBA to Python 3. @tiagocoutinho could you confirm that this reintroduces the backwards compatibility? Many thanks!
> Fix meas grp configuration URIs back compat

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/dooroutput.py
- src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py
New feature on the context menu of outputDoor, that allows the user to see debug information that was seen on doorDebug. doorDebug is now deprecated.
Fixes #965
> merge of doorDebug and doorOutput

- src/sardana/taurus/core/tango/sardana/macroserver.py
Use `os.get_terminal_size()` to determine console size instead of doing an expensive popen call.
Bonus: it works on windows ;-)
I did not use `shutil.get_terminal_size()` on purpose: it is about 500x slower and doesn't add anything useful
> Console size py3

- src/sardana/macroserver/msmacromanager.py
When an exception occurs in a macro the error message being displayed is non informative.
If, for example, a macro tries to access a non existing member ('hello') of a dict, the message is:
```
An error occurred while running Macro 'demo() -> f3e7b818-d0a1-11e9-a9ca-00':
hello
```
This PR proposes a better error message. Something like
```
An error occurred while running Macro 'demo() -> f3e7b818-d0a1-11e9-a9ca-00':
KeyError: hello
```
> Better macro exception message

- src/sardana/tango/core/util.py
instead of re-checking if we are in a no-database environment.
> MNT: use variable defined above

- src/sardana/macroserver/macro.py
Macro functions are just instances of the same MacroFunction class.
For every macro function call, the macroserver creates an instance
of MacroFunction.
The constructor of MacroFunction is already overwriting the values
of param_def and result_def so promoting hasResult() from
classmethod to method, should be sufficient to allow each macro
function to have distinct results.
> Fix #1237: Macro functions with result don't return any result

- src/sardana/pool/poolmeasurementgroup.py
This is more about measurement group's configurations backwards compatibility (Sardana migration from Taurus 3 to Taurus 4) - very similar to #1266. @tiagocoutinho could you check this? Many thansk!
MeasurementGroup's configurations created with Taurus3 were supposed to be backwards compatible when migrating to Taurus 4. Now this is broken (most probably after accepting SEP18).
Fix it by converting measurement group's timer and monitor configurations to use full URIs (scheme + FQDN in authority).
> Fix meas grp configuration URIs back compat (measurement group's timer/monitor)

- doc/source/devel/howto_macros/macros_general.rst
- src/sardana/macroserver/macros/examples/plotting.py
- src/sardana/macroserver/macros/examples/scans.py
Newer versions of ipython / matplotlib seem to miss plot call refresh when calls to plot are executed in different threads.
This PR tries to make the pyplot macro examples work correctly and gives advice in the documentation
> Make sure pyplot examples correctly refresh plot on the client

- src/sardana/taurus/core/tango/sardana/pool.py
The count_continuous method is not protected against possible
exceptions in the count_raw call (e.g. TimeOuts). Due to this the
subscription of all value buffers are kept.
This cause that the online recorder still reports the output even
the door is in alarm.
> Protect against exceptions in MeasurementGroup.count_continuous

- src/sardana/taurus/core/tango/sardana/macroserver.py
Fix sardana clients which don't have an interactive terminal attached to them
> Protect get_terminal_size() call introduced by #1245

- src/sardana/macroserver/scan/gscan.py
To determine if a channel is proceeding from Sardana or is an arbitrary Tango attribute it is enough to use TangoDeviceNameValidator.
@sardana-org/integrators could you please take a look on this one? @tiagocoutinho this may also improve the issues that we observe at BL04 so it would be nice if you could test it as well. Thanks to all!
> Avoid unnecessary creations of DeviceProxies in ascanct

- src/sardana/pool/pool.py
- src/sardana/pool/poolelement.py
- src/sardana/tango/pool/PoolDevice.py
AddDevice is called on init_device. Call DeleteDevice on delete_device.
This is done for all elements proceeding from a controller e.g. motor, counter/timer, pseudomotor, pseudocounter, etc.
We have discovered this when working with @tiagocoutinho on [sardana-ni660x](https://github.com/ALBA-Synchrotron/sardana-ni660x/blob/master/sardana_ni660x/ctrl/Ni660XCTCtrl.py) at BL04 at ALBA. There we have realized that the DeleteDevice is not called on the server shutdown. It is only called when one call DeleteElement command on the pool. @sardana-org/integrators you are welcome to review this. @tiagocoutinho could you also test it at the beamline, please. Many thanks!
> Call controller's DeleteDevice when Tango calls delete_device

- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolaction.py
- src/sardana/pool/poolbaseelement.py
- src/sardana/pool/poolmotion.py
This PR fixes two problems which affects very fast operations.
**Problem affecting acquisitions**
Since 6a80fdc ctrls were reset as _finish_hook_ to allow free readout of Value and ValueRef attributes after acquisition has finished (after SEP17 this won't be needed cause Sardana will always keep in memory the last acquisition results).
This is buggy in the case of very fast acquisitions - the elements were already released from the acquisition context and new acquisition could overlap with the finish_hook.
Avoid this problem by resetting the controllers in the custom `AcquisitionBaseContext`.
**Problem affecting motions and acquisitions**
`OperationConext` is wrongly cleared twice - within the `action_loop` and when the `OperationContext` exits. In the case of fast motions and …
> Fix clear operation (motion & acq) and reset of acq ctrls dicts

- src/sardana/macroserver/scan/gscan.py
- src/sardana/sardanathreadpool.py
Tango is not thread safe when using threading.Thread. One must use
omni threads instead. This was confirmed for parallel event subscriptions
in https://github.com/tango-controls/pytango/issues/307.
Customize taurus ThreadPool worker threads (https://github.com/taurus-org/taurus/pull/1081) to use
EnsureOmniThread (https://github.com/tango-controls/pytango/pull/327). Do it for:
* `sardanathreadpool.get_thread_pool` (global thread pool used in actions
and dummy TG)
* `CAcquisition._thread_pool` (used to execute value_buffer callbacks -
these employ recorders which could potentially subscribe to
Tango events)
For the moment don't protect:
* `ThreadPool` used by `FuncGeneratorTestCase.thread_pool` (tests - so it is controlled usage)
* `threading.Thread` used by `PoolMonitor` (not really used) …
> Protect worker threads with tango.EnsureOmnitThread

- src/sardana/pool/poolmotorgroup.py
- src/sardana/pool/poolpseudomotor.py
- src/sardana/tango/core/util.py
As it was already identified in https://github.com/sardana-org/sardana/pull/663#issuecomment-357734482 `AttributeProxy` creation could be avoided and device `WAttribute` object could be used directly. Do it for pseudo motors and motor groups to avoid problems due to https://github.com/tango-controls/pytango/issues/315.
@tiagocoutinho it would be great if you could review it - it affects BL04 at ALBA. Thanks a lot!
> Avoid using AttributeProxy when checking limits

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/common.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/dooroutput.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/favouriteseditor.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/historyviewer.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/customeditors/senv.py
- src/sardana/taurus/qt/qtgui/extra_sardana/showscanonline.py
https://github.com/taurus-org/taurus/pull/1089 changes default behavior of cmd_line_parser kwarg of TaurusApplication. If not passed Taurus won't provide any parser. Use get_taurus_pareser (OptParse) and pass it to the TaurusApplication.
> Adapt to new taurus behavior of cmd_line_parser

- src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
- src/sardana/pool/poolcontrollers/DummyTwoDController.py
When StartAll method is not called StateOne and ReadOne raises
exception - start_time is not set. Avoid this problem by detecting and
dealing especially with this situation.
Note that this most probably fixes #1188 - in the said test the measurement group is stopped after 200 ms. It may be that if the stop interrupts the start then the subsequent StateOne will fail. I will rebuild it several times. If I don't see this test to fail I will merge it myself.
> Fix dummy C/T and 2D ctrls in the case of unfinished start

- src/sardana/pool/poolcontrollers/DummyMotorController.py
In Sardana Motor velocity assumes user unit / s. Dummy controller interprets it in steps / s. Fix it and consider step_per_unit.
@sardana-org/integrators can you please take a look. This is very trivial change. Many thanks!
> Fix dummy motor velocity

- src/sardana/sardanacustomsettings.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/historyviewer.py
- src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/model.py
This is a very old issue. It was reported again at the last follow-up meeting by MaxIV.
Macroexecutor history may grow infinitely. This slows down the GUI operation (startup and changing of the perspectives). Limit the macroexecution hitory to 100. Allow to change it using the sardanacustomsettings.
If one was using macroexecutor before and have stored already more than the _limit_ macros in the history, then at the next GUI startup it will only load the last _limit_ executed macros. The rest of them will be lost.
I propose 100 as the _limit_. This can be changed with the `sardanacustomsettings`.
@julianofjm, @aureocarneiro could you test and review it?
> Limit macroexecutor history

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/ui/MacroButton.ui
The minimum size the `MacroButton` (calculated by default by Qt) is too large in some cases.
Set the minimum size of the MacroButton widget to a smaller value (25x15 pixels for the button, plus whatever it is for the frame and the bar).
It can be seen by running the following snippet and reducing the widget size with the mouse:
```python
from taurus.qt.qtgui.application import TaurusApplication
from sardana.taurus.qt.qtgui.extra_macroexecutor.macrobutton import MacroButton
if __name__ == '__main__':
import sys
app = TaurusApplication(cmd_line_parser=None)
w = MacroButton()
model = 'door/bl97/1'   # <--your door name here
w.setModel(model)
w.setMacroName('lsmac')
w.ui.button.setText('a')    
w.show()   
sys.exit(app.exec_())
```
> Allow MacroButton widget to be smaller

- src/sardana/macroserver/macros/examples/scans.py
Hi,
we've discovered a bug in regscans. When starting point of a region is the same as the starting position, scan point is repeated twice (basically one of them is not ommited).  
Example of this bug below (see points 7-8 and 18-19):
```
Door_test_1 [34]: rscan mot01 0.5 0 0.5 2 0 5 -0.5 5 0 5 0.5 5 0 2
Scan #18 started at Mon Apr 27 16:10:16 2020. It will take at least 0:00:15.981031
#Pt No    mot01      ct01      ct05     epoch       dt   
0         0        0.5       0.5     1.588e+09  0.174259
1        0.25      0.5       0.5     1.588e+09  0.891304
2        0.5       0.5       0.5     1.588e+09  1.60174 
3        0.4       0.5       0.5     1.588e+09  2.26886 
4        0.3       0.5       0.5     1.588e+09  2.93647 
5        0.2       0.5       0.5     1.588e+09  3.61776 
6 …
```
> Fix regscans points repeat

- doc/source/conf.py
- doc/source/devel/api/api_test.rst
- doc/source/users/spock.rst
- src/sardana/macroserver/macros/test/base.py
- src/sardana/pool/controller.py
The documentation builds started to fail due to PyTango intersphinx mapping problems.
These appeared to be solved with the latests Sphinx. I made some effort to fix warnings after the Sphinx upgrade.
I take a profit of this PR to set default role in docs to obj. This way one could create cross-references (even intersphinx) with just back-quotes e.g.\`taurus.Device\` instead of :obj:\`taurus.Device\`
This is a house-keeping PR, so I won't bother you with the reviews and whenever it gets green in Travis I will auto-merge.
Initially it will fail - still waiting for a new version of docker image with the Sphinx v3. But I will retrigger later..
> Build docs with Sphinx 3

- src/sardana/macroserver/macros/standard.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/taurus/core/tango/sardana/pool.py
MeasurementGroup may get into the FAULT state mainly due to these three reasons:
* software synchronized acquisition startup (load or start sequence) fails  
* one of its channels reports FAULT state
* the last readout of State or Value/ValueRef fails.
This is only reported to the user with the exception message: `Exception: Measurement group ended acquisition with Fault state`.
Similarly to dumping information about moveables when motion fails also dump it for channels in the case the measurement group acquisition fails. 
This is something what we discussed on the last follow-up meeting based on a poor experience when debugging a problem at DESY. I think this PR adds more verbosity about the measurement group problems. For example, now we would get:
```
Door_zreszela_1 [17]: ascan mot01 …
```
> Dump info on channels if MG acq fails in step scan, ct and uct 

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
PMTV was setting an encoder model on readWidget setModel. Added code that checks if the motor has an encoder before creating the model.
Fixes #209
> Pmtv relies on encoder

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
Icons now are labels instead of buttons. They have a more intuitive icon and reflect correctly all the limit states. Indicating with the text information if the active limit is software or hardware.
Here's an example on how all the states look:
The states are in this order:
> Disabled, Enabled, Software Active, Hardware Active.
To see if the which type of active is, put the cursor on the icon to display text information.
This changes also Fixes #210 
Limits on PMTV:
> New style and text information for limit icons

- setup.py
- src/sardana/taurus/qt/qtgui/extra_pool/formitemfactory.py
A recent PR in taurus (https://github.com/taurus-org/taurus/pull/1108) provides a new entrypoint for registering "TaurusValue item factories" (the entry point group name is "taurus.qt.taurusform.item_factories" )
Register one such factory to achieve the same result as with the old T_FORM_CUSTOM_WIDGET_MAP (i.e., using PoolMotorTV, etc. for sardana elements in a
TaurusForm)
If this PR is integrated, it can then easily be adapted to provide the same that was attempted with https://github.com/taurus-org/taurus/pull/1101, which is related to #1203
> Register a TaurusValue factory for pool widgets

- src/sardana/pool/poolcontrollers/DummyOneDController.py
Commit 223cdf7 wrongly removed the cast assuming that in Python 3 //
operation always returns integer number. This however depends on the operands
types. When one of the operands is float, the result is float. Here we are
dividing times which are floats. Re-introduce the cast.
The rest of the said commit is ok cause it was actually removing float casts
for / operations which in Python 3 always return float.
Note to @sardana-org/integrators: this is a revert of wrongly introduced change (done by me:) I will auto-mege it if no negative voices in the next days.
> Fix dummy 1D: cast to int number of new frames

- CHANGELOG.md
- doc/source/devel/api/api_measurementgroup.rst
- doc/source/devel/api/sardana/pool/poolsynchronization.rst
- src/sardana/macroserver/macros/expconf.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolcontrollers/test/test_DummyTriggerGateController.py
- src/sardana/pool/pooldefs.py
- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/pool/poolsynchronization.py
- src/sardana/pool/test/test_acquisition.py
- src/sardana/pool/test/test_measurementgroup.py
- src/sardana/tango/pool/MeasurementGroup.py
- src/sardana/tango/pool/test/test_measurementgroup.py
- src/sardana/taurus/core/tango/sardana/pool.py
- src/sardana/taurus/core/tango/sardana/test/test_measgrpconf.py
As agreed in https://github.com/sardana-org/sardana/pull/867#issuecomment-561742834 this PR renames the MeasurementGroup's Synchronization Tango attribute, core property and Taurus extension methods.
In the above discussion there were two votes in favor of `SynchronizationDescription` (@teresanunez and @droldan) since this is more descriptive and one in favor of `SynchronizationPlan` (@rhomspuron) since this is shorter.
Finally I had chosen the name `SynchDescription` which I think is a good compromise between these two arguments. Hope you like it. 
This PR also:
* adds the `getSynchronization` and `setSynchtronization` MeasurementGroup configuration methods and their tests
* adds the synchronization parameter to `get_meas_conf` and `set_meas_conf` macro.
I will automerge if travis is …
> Rename Synchronization to SynchDescription

- src/sardana/macroserver/macros/env.py
- src/sardana/macroserver/macros/examples/parameters.py
- src/sardana/macroserver/macros/examples/scans.py
- src/sardana/macroserver/macros/examples/submacros.py
- src/sardana/macroserver/macros/expert.py
- src/sardana/macroserver/macros/lists.py
- src/sardana/macroserver/macros/scan.py
- src/sardana/macroserver/macros/standard.py
Remove use of `ParamRepeat` which is deprecated. It generates problem when is used on macro decorator `@macro` in openSuse 11.4 (python 2.6). I changed the code to use lists.
> Remove use of ParamRepeat

- src/sardana/pool/test/test_ctacquisition.py
Now, there is a default software synchronizer in the measurement group and the test can be re-enabled. Alos correctly retrieve the Value attribute value.
I will auto-merge as soon as CI get's green  cause it is a test temporarily disabled in the past and later on forgotten to be re-enabled.
> Reintroduce MeasurementGroup test_acquisition

- src/sardana/taurus/core/tango/sardana/pool.py
A deadlock may happen between a thread using the said methods and
the *Tango Event Consumer* thread. The first one locks the `AttrEventWait`
object while the second one locks the Tango event system.
It was observed when using the Sardana-Taurus model extension of
the measurement group which executes `PoolElement.start()` which
basically waits for the measurement group being in a state != MOVING,
then executes the `Start` command and then wait for state == MOVING.
What happens is that while executing the `Start` command the GC enters
and destroys some Taurus device created previously. Meanwhile,
a state event already arrives and `AttrEventWait.fireEvent()` triggered
from the `TangoAttribute.push_event()` waits for the lock.
This lock will never get released cause the …
> Remove redundant protection in PoolElement.start() and waitFinish()

- .travis.yml
- CHANGELOG.md
- doc/source/devel/howto_test/test_general.rst
- doc/source/devel/howto_test/test_run_commands.rst
- setup.py
- src/sardana/tango/macroserver/test/base.py
- src/sardana/tango/pool/test/base.py
- src/sardana/tango/pool/test/test_persistence.py
- src/sardana/test/testsuite.py
Current sardanatestsuite duplicates some tests. Approx 50 tests are executed twice making the whole test sute longer of more than 4 min.
See for example: [this job](https://api.travis-ci.org/v3/job/694553069/log.txt) where:
```
test_meas_cont_acquisition_4 (sardana.pool.test.test_measurementgroup.AcquisitionTestCase)
```
is executed twice.
It seems like a bug in Python unittest - it is already `TestLoader.discover()` which returns duplicated tests.
Instead of investigating it change the test runner to pytest which could open doors for other interesting features comming with pytest.
Note that previously I have installed the latest pytest in sardana-test docker image.
> Run sardana tests with pytest

- src/sardana/macroserver/macros/standard.py
- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolaction.py
- src/sardana/pool/poolbasechannel.py
- src/sardana/pool/poolbasegroup.py
- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/pool/poolpseudocounter.py
- src/sardana/pool/poolsynchronization.py
- src/sardana/pool/test/test_acquisition.py
- src/sardana/sardanaattribute.py
- src/sardana/sardanadefs.py
- src/sardana/tango/core/util.py
- src/sardana/tango/pool/CTExpChannel.py
- src/sardana/tango/pool/test/base_sartest.py
- src/sardana/tango/pool/test/test_measurementgroup.py
- src/sardana/taurus/core/tango/sardana/test/test_measgrpstress.py
When trying to get some base line numbers for #161 I realized that fast repetitions of measurement group counts is buggy. There were basically two major issues which this PR solves:
* The software synchronized acquisition action from one execution of the measurement could find the previous acquisition still in progress. This was solved for acquisition within one measurement with multiple repeats but was buggy for multimple measurements with one repeat. 292fcea and 076a015 fixes it.
* Pre-mature setting of state used for determining the *Value* Tango attribute quality (CHANGING when state is MOVING and VALID when state is ON) was causing that the measurement group state event was being pushed too early - more details in 054ebab and 90db657
This PR also:
* itnroduces attribute quality in …
> Fix fast measurement group acquisitions

- src/sardana/pool/poolacquisition.py
Acquisition's `action_loop()` exits the state poll loop when none of the
elements is in Moving or Running state. This indicates that the acquisition
has finished. This last state readout should be propagated to the
channels. Avoid the extra state readout which actually could change the
end acquisition state. This also introduces a small performance improvement - #161
> Avoid extra state readout at the end of acquisition

- doc/source/conf.py
- doc/source/devel/api/sardana/pool/poolutil.rst
- doc/source/devel/howto_controllers/howto_controller.rst
- doc/source/devel/howto_macros/macros_general.rst
- doc/source/users/faq.rst
- src/sardana/pool/poolutil.py
This documentation was requested by one of our scientists at ALBA. When migrating user macros to Python 3 we discovered that user macros were using several different ways of accessing to Tango devices. 
I tried to summarize what possibilities we have and give a simple rule of thumb on which one to use.
There is one more way which I have not documented yet. The `Macro.getDevice()` which currently does not give any benefit over `taurus.Device()`. But with the recent investigation of @tiagocoutinho on how Tango (and CORBA) optimizes socket connection from the client to the server I think we could change this method and make it maintain the reference to the `taurus.Device`. It is similarly done for the internal Sardana elements getters e.g. `getMotor`. @tiagocoutinho, if I understood well the …
> Add docs on how to access Tango in macros and controllers

- src/sardana/macroserver/macro.py
- src/sardana/macroserver/macros/examples/parameters.py
- src/sardana/macroserver/macros/examples/scans.py
- src/sardana/macroserver/msmetamacro.py
- src/sardana/macroserver/msparameter.py
Also correct some examples and docstrings.
> Remove deprecated ParamRepeat (4)

- src/sardana/macroserver/scan/gscan.py
> Remove deprecated hookplaces: hooks and pre-start (5,6)

- src/sardana/macroserver/macros/examples/specific_experiments.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/macroserver/scan/recorder/storage.py
> Remove deprecated FileRecorder macro hint (7)

- src/sardana/pool/controller.py
- src/sardana/pool/poolcontrollers/HklPseudoMotorController.py
- src/sardana/pool/poolmetacontroller.py
> Remove deprecated Controller API (8-14, 31)

- src/sardana/pool/controller.py
> Remove deprecated PseudoMotorController API (20-23)

- src/sardana/pool/controller.py
> Remove deprecated PseudoCounterController API (24)

- src/sardana/pool/controller.py
- src/sardana/pool/poolcontrollers/DummyIORController.py
- src/sardana/pool/poolmetacontroller.py
> Remove deprecated IOR predefined_values (25)

- doc/source/devel/howto_controllers/howto_countertimercontroller.rst
- doc/source/devel/howto_controllers/sf_ct_ctrl.py
- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolcontrollers/DummyOneDController.py
- src/sardana/pool/poolcontrollers/TaurusController.py
> Remove deprecated LoadOne backawards compatibility (26, 27, 48, 49)

- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/tango/pool/test/test_measurementgroup.py
> Remove backwards compatibility for measurement group start without preparation (30)

- src/sardana/tango/macroserver/Door.py
> Remove deprecated Door's Abort command (41)

- src/sardana/taurus/core/tango/sardana/pool.py
> Remove Controller's (Taurus extension) getUsedAxis method (42)

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/dooroutput.py
> Remove deprecated DoorAttrListener class (43)

- src/sardana/pool/poolcontrollers/DiscretePseudoMotorController.py
> Remove deprecated DiscretePseudMotor Label and Calibration attributes (38)

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
> Remove deprecated methods from MacroButton widget (44, 45, 46)

- ci/appveyor.yml
In ccfd7066 I tried to adapt the appveyor configuration file to build python 3 packages without success. This PR is just trying to fix it and rebuild on appveyor without pushing to the release branch. Whenever I'm satisfied I will squash the attempting commits and push it to the release branch.
> Fix appveyor configuration (python3)

- src/sardana/taurus/core/tango/sardana/pool.py
(This PR suggests the same changes as #1396 but goes to the release-Jul20 branch)
#1069 demonstrated that poor time precision on Windows affects the `AttributeEventWait` mechanism of events recognition.
During Jul20 release (3.0.2) tests the same problem was found in the `PoolElement.waitFinish()` and more preciselly in the measurement group's acquisitions.
The following debugging traces demonstrates it:
1. Lines starting from _waitEvent..._ print the `AttributeEventWait.waitEvent()` arguments.
2. Lines with the dictionary string representation print the _event set_ at the beginning of each iteration which looks for the event condition.
```
SardanaTP.W002 DEBUG    2020-08-26 08:53:15,111 Door/demo1/1.Macro[ct]: Counting for 1.0 sec
SardanaTP.W002 OUTPUT   2020-08-26 08:53:15,111 …
```
> Fix premature end of acquisition on Windows

- src/sardana/spock/magic.py
- src/sardana/util/whichpython.py
On some OS Python 3 is executed with python3 but in conda environments it is executed with python. Use proper Python 3 executable regardless of the Python installation.
@sardana-org/integrators could you please take a look. IMO it is release critical.
Many thanks!
> Use proper python3 executable regardeless of installation

- src/sardana/pool/controller.py
#1362 wrongly changed the `CounterTimerController` API and made the `StartOne()` re-implementation mandatory.
Re-introduce the previous API.
Note: for `OneDController` and `TwoDController` controller the re-implementation is still mandatory as it was before.
@sardana-org/integrators I will auto-merge it.
> Make CounterTimerController.StartOne() re-implementation optional

- src/sardana/macroserver/scan/gscan.py
- src/sardana/taurus/core/tango/sardana/pool.py
`timescan` and `TScan` does not handle the referable channels. Subscribe to them to make `tiemscan` compatible with referable channels.
Fix #1399.
@13bscsaamjad could you please review and test this one? Many thanks!
> Fix timescan with referable channels

- src/sardana/spock/magic.py
Showscan without arguments should open showscan offline. When scan ID
is given as argument it should open the corresponding scan.
> Fix showscan offline broken in #1260

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py
This PR fixes the macrobutton's main section by avoiding usage of the methods removed in https://github.com/sardana-org/sardana/pull/1379.
@sardana-org/integrators I will auto-merge it since this change was agreed in #1315.
> Fix macrobutton main method

- src/sardana/macroserver/macros/scan.py
This PR adds some additional protections to the `scanstats` macro:
* return from the macro if the parent scan does not involve moveable e.g. `timescan`
* return from the macro if there is no enabled scalar channel in the measurement group e.g. 1D and 2D channels are not allowed (these may be referable)
There is one more thing which maybe could be improved. If we use software synchronization in continuous measurements some acquisitions may be skipped and channel will report `NaN`. How should the statistics behave in this case. What we have now is:
```
Door_zreszela_1 [20]: ascanct mot01 0 1 10 0.1
Operation will be saved in /tmp/test.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #328 started at Fri Aug 28 12:41:01 2020. It will take at least 0:00:00
#Pt No    mot01      ct01     gct01 …
```
> Add protections to scanstats macro

- src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
This issue was discovered in the release manual tests. 
When adding an external channel e.g. Tango attribute and then scrolling the contents of the channel's editor in the expconf the following exception was being raised:
```
Traceback (most recent call last):
File "/home/zreszela/workspace/sardana/src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py", line 529, in data
return None
KeyError: 'synchronization'
```
Similar error was also observed for PseudoCounters:
```
Traceback (most recent call last):
File "/home/zreszela/workspace/sardana/src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py", line 532, in data
synchronization = unitdict[key]
KeyError: 'synchronization'
```
This PR fixes it.
It also improves the expconf and allows to edit: Timer, Monitor, Synchronizer …
> Fix problems with non-timerable channels in expconf

- scripts/upgrade/upgrade_env.py
Do not hard-code the DS name to MacroServer. The upgrade_env.py script should be able to migrate also the Sardana DS environments.
@sardana-org/integrators could you please take a look? It is release critical.
> Fix upgrade_env.py to properly migrate environments from the Sardana servers

- src/sardana/taurus/core/tango/sardana/pool.py
This PR fixes #1415. What happens there is that the the same `MeasurementGroup` sardana-taurus model extension object is present in the MacroServer when one runs the `set_meas_conf` macro and when one runs a scan.
The `MGConfiguration.set_data()` is trying to optimize the objects recreation and was doing that also for Tango objects dictionaries. This dictionaries however apart from storing the Tango DeviceProxies also store the configuration info. If we don't reset these dictionaries then the configuration info gets outdated. This was affecting the
https://github.com/sardana-org/sardana/blob/ffbe5f36e6a11a2c2eb4cfd59e6f39dd1185c2de/src/sardana/macroserver/scan/gscan.py#L669
what in consecuence was delivering outdated `data_desc` in the RecordData event.
Note, my patch is very trivial, …
> Reset MGConfiguration tango internals also if changes proceeds from the same object

- src/sardana/macroserver/scan/test/helper.py
it fixes:
-  a typo of parameter name in a call to ScanData.addData in the test scan helper
- format of starttime in the test DummyEventSource
> add fix for a parameter of addData and starttime value

- src/sardana/macroserver/macros/scan.py
Per measurement preparation in deterministic scans is done based on the `integ_time` and ~`nb_starts`~ `nb_points` attribute presence in the macro obj.
Add ~`nb_starts`~ `nb_points` attribute to the mesh macro.
This PR is the outcome of a pair-programming session with @13bscsaamjad. Can some of @sardana-org/integrators take a look, please. Many thanks!
> Execute per measurement preparation in mesh

- src/sardana/pool/poolacquisition.py
- src/sardana/pool/test/test_acquisition.py
@jordiandreu and @rhomspuron found a bug in hardware synchronized by start trigger acquisitions with referable channels.
The controller's `RefOne()` are called only once at the end of the acquisition but should be also called continuously during the acqusition.
This PR fixes it. I've also added tests, both, to reveal the problem and some regression tests for the `ReadOne()` calls which curently work fine.
> Fix continuous readout of value references in hardware synchronized acquisition

- .travis.yml
This job execution reveals problem with the flake8 test:
https://travis-ci.org/github/sardana-org/sardana/jobs/745428261
This issue appeared after recent new release of flake8 
and is due to the way we install flake8 on travis.
Even it it should be relatively easy to fix, I think we should not invest time
to travis since we will move to some other CI solution (see #1433).
I will auto-merge when it gets green again.
> Disable flake8 job in travis CI

- src/sardana/tango/pool/PoolDevice.py
When adding attributes the controller code can modify them e.g. format, type, maxdimsize. Make a copy of the standard class attributes proceeding from the class definition to avoid problems with modifying them.
Fixes #1440.
> Leave Tango device class attributes definition untouched

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
When the motor position has units defined, the taurus motor widget shows the units in two places as can be seen here:
This PR proposes to fix it and only show on the right side of the GUI as it was before
> Fix double unit shown in motor widget

- doc/source/devel/api/sardana/macroserver/scan.rst
- src/sardana/macroserver/scan/gscan.py
Deterministic scan optimization of measurement is not compatible with
attaching measurements on the same measurement group as hooks.
Add deterministic_scan property to allow disabling this optimization.
You can try it with the following example:
```python
import functools
from sardana.macroserver.macro import macro, Type
from sardana.macroserver.scan import SScan
def count(parent):
parent.output("In count")
mnt_grp = parent.getObj(parent.getEnv("ActiveMntGrp"),
type_class=Type.MeasurementGroup)
state, data = mnt_grp.count(0.2)
parent.output(data)
@macro([["moveable", Type.Moveable, None, "moveable to get position"]])
def custom_scan(self, moveable):
"""Testing custom_scan macro"""
self.output("In custom_scan")
ret = self.createMacro("ascan", moveable, "0", "1", "1", "0.1")
my_scan, _ = …
```
> Allow to programmatically disable *deterministic scan* optimization

- src/sardana/macroserver/macro.py
Make sure we return the exact same default settings as the Macro class
(ex: tools like the sequencer GUI expect hints to be a dict)
> Fix macro function default settings

- doc/source/devel/api/api_controller.rst
- doc/source/devel/api/sardana/pool/controller.rst
- doc/source/devel/howto_controllers/howto_triggergatecontroller.rst
- doc/source/devel/howto_macros/scan_framework.rst
- src/sardana/pool/controller.py
- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolcontrollers/DummyTriggerGateController.py
Trigger/gate elements could be prepared for multiple starts in a deterministic scan and benefit from it.
- Add PrepareOne() to TriggerGate controller.
- Call preparation methods in PoolAcquision.preapre()
- Implement empty `PrepareOne` in DummyTriggerGateController
- Document the new feature
Implements #1432
This PR is the outcome of a pair-programming session with @13bscsaamjad.
> Include TriggetGate elements in the per-measurement preparation

- doc/source/devel/api/api_macro.rst
- doc/source/devel/howto_macros/macros_general.rst
- src/sardana/macroserver/macro.py
In our control room our operators started using macros for the accelerators operation. They migrated a set of python scripts into macros. We have observed that in their scripts (now macros) they were using broad exception types in the `except` clause.
This may interfer with the macro stopping/aborting. 484af30 warns about it.
Since the [How to develop macros](https://sardana-controls.org/devel/howto_macros/macros_general.html) documentation already growed to a big chapter I take a profit of this PR to add a table of contats (TOC) in order to faciltate navigation. The section headers are now links to the chapter in the TOC.
It looks more or less like this:
@sardana-org/integrators could you please take a look on this. Thanks a lot!
> Document how to properly deal with exceptions in macros

- doc/source/users/configuration/server.rst
* document the possibility to fix IP address
* fix examples to use "giop:tcp:" prefix
This is a trivial PR to add some additional infos to the docs hence I will auto-merge.
> Complement and fix docs on setting ORBendPoint

- src/sardana/pool/poolpseudomotor.py
Fix ValueError (unsupported format character ''') by properly formatting string.
For example:
```
In [1]: "foo '%'" % "bar"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-8b2d6384ce5e> in <module>()
----> 1 "foo '%'" % "bar"
ValueError: unsupported format character ''' (0x27) at index 6
```
vs.
```
In [2]: "foo '%s'" % "bar"
Out[2]: "foo 'bar'"
```
This is a trivial PR. I will auto-merge.
> Fix bug in string formatting

- src/sardana/taurus/core/tango/sardana/pool.py
Write of the integration time may fail e.g. problems with reading latency_time of the controller, and we fill the cache anyway. This causes problems with not initialized synchronization description.
Fill integration time cache only if the write worked.
> Make write of integration time more robust

- src/sardana/spock/inputhandler.py
- src/sardana/spock/ipython_01_00/genutils.py
- src/sardana/spock/magic.py
- src/sardana/spock/qtinputhandler.py
- src/sardana/spock/spockms.py
Allow launching Spock from commandline without need to have Qt bindings installed.
The behaviour is like this:
- try to detect if Qt bindings are installed (vi `import taurus.external.qt.Qt`)
- if Qt bindings are installed, use them
- if Qt bindings are not installed, use command-line only input handler.
closes #1462 
I'm not an expert in IPython or Spock hence I would appreciate testing from more advanced users.
> Allow running Spock without Qt bindings

- src/sardana/macroserver/macro.py
- src/sardana/macroserver/test/res/macros/testmacros.py
I would be useful to have the macro name and the macro line information in the macro status "start" event.
This PR adds that.
> Add macro name and line to macro status 'start' event

- src/sardana/macroserver/recorders/h5storage.py
In https://github.com/sardana-org/sardana/issues/771#issuecomment-736360038 and continuation with @dschick we were talking about storing RoI configuration in PreScanSnapshot. This was already possible using spectrum attributes (I wrongly assumed that it was not working) and this PR fixes it for strings.
```
Door_zreszela_1 [26]: lssnap
Snap item                                        Snap item full name
--------------- ----------------------------------------------------------
long_spectrum   tango://pt222.cells.es:10000/sys/tg_test/1/long_spectrum
string_scalar   tango://pt222.cells.es:10000/sys/tg_test/1/string_scalar
Door_zreszela_1 [27]: ascan mot01 0 1 1 0.1
Operation will be saved in /tmp/scan.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #16 started at Tue Jan 26 16:38:43 2021. …
```
> Fix PreScanSnapshot of strings

- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/macroserver/recorders/test/test_h5storage.py
https://github.com/sardana-org/sardana/issues/771#issuecomment-734743646 reports a bug with saving string _custom data_. This PR fixes it. @dschick, the workaround from https://github.com/sardana-org/sardana/issues/771#issuecomment-736360038 is not necessary anymore. @sardana-org/integrators could you please take a look on this one?
Note that in h5py 3.x they changed some recommendations for storing string data, but this PR still uses the recommendations from h5py 2.x that we used in the past.
> Fix NXscanH5_FileRecorder.addCustomData() with strings

- src/sardana/taurus/qt/qtgui/extra_sardana/qtspock.py
I forgot to update the example to reflect the changes in ba692bc9c1c2273da6c2d56b08bb2c9890f870d9.
It would be nice to have a better error message when no kernel is started. Currently, only `...` is shown after pressing enter in a widget without a running kernel.
> Fix example in docstring of QtSpockWidget

- MANIFEST.in
The LICENSE was missing from the Python package
> Add LICENSE to python package

- doc/source/devel/howto_controllers/howto_countertimercontroller.rst
The important commits are:
- 6429267 - Document hardware and software start synchronization
- 05549ef - Document latency time
- ec25857 - Document per measurement preparation
I took a profit of this PR to also add a TOC at the top of the chapter.
Adds #995.
@sardana-org/integrators could you please take a look on this one? Many thanks!
> Add missing SEP18 concepts to how-to counter/timer controller

- src/sardana/macroserver/macros/lists.py
- src/sardana/tango/core/util.py
- src/sardana/taurus/core/tango/sardana/macroserver.py
Starting with Python 3.8 these are reported as warnings:
The compiler now produces a SyntaxWarning when identity checks (is and is not)
are used with certain types of literals (e.g. strings, numbers).
These can often work by accident in CPython, but are not guaranteed by the language spec.
The warning advises users to use equality tests (== and !=) instead.
This is a trivial PR I will auto-merge when CI shows green light.
> Use equality instead of identity checks for numbers and strings

- doc/source/devel/api/sardana/pool/controller.rst
- doc/source/devel/howto_controllers/howto_1dcontroller.rst
- doc/source/devel/howto_controllers/howto_2dcontroller.rst
- doc/source/devel/howto_controllers/howto_countertimercontroller.rst
This PR adds documentation on how to write 1D and 2D controllers.
Since at the end 1D and 2D are _timerable_ controllers as counter/timer controller, I decided to not duplicate the documentation and just reference to the counter/timer controller documentation and list the differences and additional features.
Similarly the 1D controller documentation does not duplicate the _value referencing_ documentation which is placed in the 2D controller documentation.
These documentation does not follow the entire narration of developing "Springfield" hypothetical hardware controller as it is done for the motor and counter/timer. This would require more time and this PR just adds the strictly necessary information. This way we could advance with the last missing point from #1466. …
> Document how to write 1D and 2D controllers

- doc/source/devel/howto_controllers/howto_1dcontroller.rst
- doc/source/devel/howto_controllers/howto_2dcontroller.rst
- doc/source/devel/howto_controllers/howto_pseudocountercontroller.rst
- doc/source/glossary.rst
- doc/source/users/taurus/experimentconfiguration.rst
- src/sardana/macroserver/scan/gscan.py
- src/sardana/pool/controller.py
- src/sardana/pool/poolbasechannel.py
- src/sardana/pool/poolcontrollers/DummyOneDController.py
- src/sardana/pool/poolcontrollers/DummyTwoDController.py
- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/tango/pool/PoolDevice.py
- src/sardana/tango/pool/PseudoCounter.py
- src/sardana/taurus/core/tango/sardana/sardana.py
- src/sardana/taurus/qt/qtgui/extra_sardana/measurementgroup.py
This PR changes the experimental channel's shape: from the measurement group configuration parameter to the read only controller's axis parameter - see #1296. The main benefit of this is that it is not necessary to modify the measurement group configuration everytime the shape changes e.g. RoI or binning change. The drawbacks is that the shape is consulted on every scan start (for external channels one extra read may be necessary).
@dschick, I have published it even if it is still WIP so you could comment if it goes in the right direction. It should be pretty operable - the scan already takes into account the shape reported by the controller and ignores the shape from the measurement group configuration. If you already go for testing it please follow the example of dummies from e01ce34. …
> Change shape to read only axis parameter

- src/sardana/macroserver/msmacromanager.py
XML hooks, usually composed by the sequencer, as other hooks (programmatic or
general), needs information about the parent macro. Fill it when preparing
the macro object. See #1472 for more details.
> Fill parent_macro in case of executing XML hooks (sequencer)

- doc/source/devel/guide_migration/2to3.rst
- scripts/upgrade/upgrade_mntgrp.py
When upgrading one of our beamlines to Sardana 3 we realized that not all measurement group configurations were already converted to use the URIs in the measurement group configuration.
Sardana 3 removed the backwards compatibility as agreed in #1315.
The upgrade script from this PR may be helpful during the migration process.
> Add script to upgrade mntgrp from Sardana 2 to Sardana 3

- src/sardana/pool/poolmotor.py
Setting motor sign to 0 may lead to wrong position calculation.
Assert motor sign is -1 or 1. Fix #1345.
It works as following:
```
Door_zreszela_1 [1]: mot01.sign = 1
Door_zreszela_1 [2]: mot01.sign = -2
PyDs_PythonError: AssertionError: sign must be either -1 or 1 (not -2)
(For more detailed information type: tango_error)
Door_zreszela_1 [3]: mot01.sign = -1
Door_zreszela_1 [4]: mot01.sign = 0
PyDs_PythonError: AssertionError: sign must be either -1 or 1 (not 0)
(For more detailed information type: tango_error)
```
@sardana-org/integrators could you please review. Many thanks!
> Assert motor sign is -1 or 1

- src/sardana/taurus/core/tango/sardana/macroserver.py
_get_macroserver_for_door() is assuming that the macroserver belongs to the default Tango database. In case the door is
a remote door (on different Tango database) the macroserver is never found. Fix it by interrogating the Tango database of the door and by creating a macroserver device from full name.
I found it using a similar macro to this one:
```python3
import taurus
from sardana.macroserver.macro import macro
from sardana.taurus.core.tango.sardana.macroserver import registerExtensions
registerExtensions()
@macro()
def foo(self):
door = taurus.Device("tango://pt222.cells.es:10000/Door/test/1")
door.runMacro("bar", synch=True)
```
@sardana-org/integrators could you please take a look?
@cpascual maybe you know a better way of creating full name than: `full_name = db.getFullName() + "/" …
> Fix getting macroserver from remote door

- src/sardana/taurus/core/tango/sardana/motion.py
Move of motion object sends motors to wrong positions. This happens when using moveables from different Pools and is not 100 % reproducible.
This is due to the fact that we rely on simple dictionaries (their order is not preserved in Python 3.5) when constructing the Motion object from the list of moveables requested by the user. Further move requests on that object assume that the positions correspond to the order of moveables requested at the Motion object creation time. Currently the order may be lost.
Use OrderedDict instead to avoid such problems.
We discovered this bug after migrating one of our beamlines to Python 3, while executing continuous scan (a2scanct). I looks like with Python 2 we were more lucky and we had not suffered it. Before reviewing it, let's wait until …
> Ensure order of moveables is preserved in Motion object

- src/sardana/macroserver/msenvmanager.py
Empty environment files used with dumb backend fails to
open with 'w' flag. This does not happen for gdbm backend.
Avoid this problem by always using 'c' flag, which according to
docs [1]: "Open database for reading and writing, creating it if it doesn’t exist".
Tested and it does not harm when the environment shelve files is not empty - its
content is preserved.
Fixes #1425.
[1] https://docs.python.org/3/library/dbm.html#dbm.open
> Open msenvironment shelve file always with 'c' flag

- src/sardana/macroserver/msenvmanager.py
Reverts sardana-org/sardana#1514
This PR leads to wrong creation of new environment file with `ndbm` backend on top of already existing, empty, `dumb` backend.
This was reported by @teresanunez in https://github.com/sardana-org/sardana/pull/1514#issuecomment-794113215.
> Revert "Open msenvironment shelve file always with 'c' flag"

- src/sardana/macroserver/macro.py
- src/sardana/macroserver/test/test_macro.py
- src/sardana/macroserver/test/test_msparameter.py
When working on #1480 we discovered that `Hookable.hooks` property could not be set to empty list. Fix it and add automatic tests.
Not related to this, in a6b55a6, I add a missing header with the license.
@sardana-org/integrators, whenever CI allows me, I will auto-merge since this is a trivial bug-fix and it will speed-up work on #1480. Feel free to comment anyway and I will apply corrections afterwards.
> Fix hookable set hooks to empty list

- src/sardana/taurus/core/tango/sardana/macro.py
Macro.hasResult() and Macro.hasParams() wrongly returns True if the result
and params definition is an empty list. This leads to adding empty:
"Parameters" and "Result" sections in the macro's description in Spock.
Fix it and consider empty lists as no parameters and result.
This changes macro's description from:
```
Door_zreszela_1 [1]: ascan?
Docstring:
Syntax:
ascan <motor> <start_pos> <final_pos> <nr_interv> <integ_time> -> 
Do an absolute scan of the specified motor.
ascan scans one motor, as specified by motor. The motor starts at the
position given by start_pos and ends at the position given by final_pos.
The step size is (start_pos-final_pos)/nr_interv. The number of data
points collected will be nr_interv+1. Count time is given by time which
if positive, specifies seconds and if …
```
> fix: Macro.hasResult() and Macro.hasParams()

- doc/source/devel/api/sardana/taurus/core/tango/sardana.rst
- doc/source/devel/api/sardana/taurus/core/tango/sardana/macro.rst
- src/sardana/taurus/core/tango/sardana/macro.py
As mentioned in https://github.com/sardana-org/sardana/pull/1480#issuecomment-799800371 I added "Allowed hooks" to the macro description, e.g.:
```
Door_zreszela_1 [1]: ascan?
Docstring:
Syntax:
ascan <motor> <start_pos> <final_pos> <nr_interv> <integ_time> -> 
Do an absolute scan of the specified motor.
ascan scans one motor, as specified by motor. The motor starts at the
position given by start_pos and ends at the position given by final_pos.
The step size is (start_pos-final_pos)/nr_interv. The number of data
points collected will be nr_interv+1. Count time is given by time which
if positive, specifies seconds and if negative, specifies monitor counts.
Parameters:
motor : (Moveable) Moveable to move
start_pos : (Float) Scan start position
final_pos : (Float) Scan final position …
```
> Add allowed hooks to macro description in Spock

- src/sardana/pool/poolbasegroup.py
As proposed in https://github.com/sardana-org/sardana/pull/1474#issuecomment-805937733 this PR cherry-picks from #1474 the commits which fix #1421. The rest of the commits, the ones which provide the automatic tests, stay in #1474.
> Set stop flags for each element in multiple elements movement

- src/sardana/macroserver/macros/standard.py
PoolMotion action at the very end emits first the position event
and then the state event. If the mv macro, which is internally
executed by the umv macro, finished, then we can assume that no
more position events will arrive corresponding to the requested
move. This is because the mv macro finishes only after the state
transition which is based on the event and we are executing
the events callback sequentially. The event emission order is
preserved on the client side according to:
https://www.tango-controls.org/community/forum/c/general/development/is-events-order-maintained
Removing of this extra print also improves the behaviour when
post-move hooks use macro logging as described in #1480.
> perf: remove redundant print of positions at the end of umv

- src/sardana/pool/poolbasechannel.py
Value is read in a worker thread, however the read synchronizes with the worker
thread anyway in order to return the read value.
Read it in serial mode to avoid extra complexity of involving a thread.
It is also done the same way for the motor's dial position readout.
> Read value in serial mode

- doc/source/conf.py
- src/sardana/macroserver/macro.py
- src/sardana/tango/macroserver/MacroServer.py
Docstring using the Numpy style, e.g. as proposed in 321b6a6, cause warning "Unexpected section title". Enable sphinx napoleon extension to avoid this warning and preprocess other styles in addition to a pure rst.
Also, fix two warnings that appeared after enabling this extension.
Soon, I will open an issue to discuss the preferred docsting style, if we actually need an alternative to a pure rst.
This also depends on installing sphinxcontrib-napoleon which should be already available in [sardana-test](https://github.com/reszelaz/sardana-test/commit/3480c875e91b3baf06bb54c432a15b963a3425f4)
> Enable sphinx napoleon extension

- src/sardana/pool/poolmeasurementgroup.py
timer/monitor configuration parameters are still kept in the measurement
group configuration for the backwards compatibility. Respect the user
configuration values (if present) otherwise fill it with the software
master timer/monitor or a random timerable channel (last fallback).
> respect timer/monitor passed in measurement group configuration

- src/sardana/tango/core/SardanaDevice.py
- src/sardana/tango/core/util.py
- src/sardana/tango/macroserver/MacroServer.py
Add sardana_init_hook to SardanaDevice for allowing the subscribe to pool's elements attribute in the init of the MacroServer.
Based on the response of Michal to https://gitlab.com/tango-controls/pytango/-/merge_requests/419. Modify the run_tango_server to replicate the behavior of post_init_callback found in PyTango High-level API which is invoked before the server enters the event loop. Fixes #674.
> Add sardana_init_hook

- CHANGELOG.md
- src/sardana/macroserver/macros/hkl.py
- src/sardana/macroserver/macros/standard.py
- src/sardana/sardanacustomsettings.py
This PR adds the `pre-move` & `post-move` hook places to `mv` macro.
A new `sardanacustomsetting ` parameter named `PRE_POST_MOVE_HOOK_IN_MV` is introduced to disable the `pre-move` and `post-move` hook places in the `mv` macro by default.
> Fix #1471: add pre-move & post-move hook places to mv-macro

- src/sardana/macroserver/test/test_msrecordermanager.py
Fix test failing on Windows due to using wrong path separator.
Use os.pathsep instead of hardcoding ":" in recorder paths
(test input). For windows the separator must be ";".
> (test) use os.pathsep as recorder paths separator in test.

- src/sardana/tango/pool/test/test_measurementgroup.py
Wrong full_name composition makes the test to fail
(surprisingly only on Windows)
TangoDeviceNameValidator is not capable to interpret the
device names containing authority which does does not start
with "//". Add this prefix to avoid the problems.
Sardana does not support Taurus 3. Also remove unnecessary fallback.
> Fix measurement group tango test

- src/sardana/macroserver/msdoor.py
- src/sardana/macroserver/msmacromanager.py
Macro which was already finished is considered as _running
macro_ and at the MacroServer (MS) exit the running macro gets
aborted. This abort is unnecessary and causes the MS to crash
on Windows.
- Introduce the concept of _last macro_.
- When the macro finishes, update the _last macro_ information
and at the same time clear the _running macro_ - this avoids
the macro aborting.
- Maintain the backwards compatibility when reading the macro
data from the door: if it is read during the macro execution
it reports the data of the macro currently being run and as
soon as the macro finished it returns the data of the macro
which just finished execution.
> (fix) Avoid already finished macro being aborted at MS exit

- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/macroserver/recorders/test/test_h5storage.py
Some fixes required for having hdf5 with VDS feature working.
Identified so far:
* if no vds name is given in ValueRefPattern it should default to "dataset" but instead is defaulting to None which raises error
* in some versions of h5py (example: 3.1) you get "bytes" instead of "str" as value for a key which raises an error
A more serious error is that when vds is active for a specific channel, the vds shape is taken from the channel (which gets it from the controller) but the dtype is the same of the original even which is "str" since the channel provides the data source in form of a URI. hdf5 raises an error saying that it cannot create a vds for type "<U" as seen below:
```
spock --profile=myth2
Spock 3.0.3 -- An interactive laboratory application.
help      -> Spock's help system. …
```
> Fixes for string datasets with h5py >= 3

- src/sardana/macroserver/recorders/test/test_h5storage.py
This PR improves the h5storage tests so they pass on Windows and mark the `test_VDS`  as xfail (see #1562).
See the particular commit messages for more details.
> Make h5storage tests pass on WIndows

- src/sardana/tango/macroserver/test/macroexecutor.py
- src/sardana/tango/pool/test/test_measurementgroup.py
Some combination of tests (when not executed with other tests
using Taurus >= 4.7.1) crash at exit due to [PyTango#390](https://gitlab.com/tango-controls/pytango/-/issues/390).
Register (at class level) atexit hook to call `tango.ApiUtil.cleanup()` in:
- `MacroExecutor` (tango implementation) - used when testing
macro execution
- MeasurementGroup (tango) tests
Multiple executions of `ApiUtil.cleanup()` does not harm.
> (test) Avoid crashes of tests at process exit

- src/sardana/tango/pool/test/base_sartest.py
- src/sardana/tango/pool/test/test_Motor.py
- src/sardana/tango/pool/test/test_measurementgroup.py
- src/sardana/tango/pool/test/test_persistence.py
- src/sardana/taurus/core/tango/sardana/test/test_measgrpconf.py
- src/sardana/taurus/core/tango/sardana/test/test_measgrpstress.py
- src/sardana/taurus/core/tango/sardana/test/test_pool.py
Calling Pool's DeleteElement() command at the end of the tests very often crashes the server on Windows (it may have to do with pushing change event on the Elements attribute just before the server exit, note that this is not problematic on Linux).
This deletion is not necessary cause at the end the device server will be deleted anyway.
Skip execution of this command on Windows.
Fixes #540.
> (test) avoid executing Pool's DeleteElement() cmd on Windows

- src/sardana/taurus/qt/qtgui/extra_sardana/test/test_qtspock.py
qtspock's `test_get_value()` fails with newer versions of qtconsole. 
This is because `RichJupyterWidget.blocking_client` (`BaseFrontendMixin.blocking_client`) was removed in [qtconsole#174](https://github.com/jupyter/qtconsole/issues/174) and is not available in qtconsole >= 4.4.0.
Skip the test for these versions.
@schooft do you have other ideas on how to deal with that? Many thanks in advance!
> (test) skip qtspock test_get_value if qtconsole >= 4.4.0

- src/sardana/taurus/qt/qtgui/extra_sardana/qtspock.py
Setting qtspock's prompt (door's alias) fails when traitlet >= 5.0.0 and Taurus models are used instead of configuration stored in the profile. This is because the traitlets library instead of returning a string door_alias now returns DeferredConfigString object.
Fix it by obtaining a string value stored in this trait.
@schooft, first many thanks for providing unit tests together with the qtspock. These made us realize that with the new versions of the traitlets package the qtspock prompt was not correctly set (currently our CI does not run the tests with the newest versions of the packages and I just run them manually as part of the Jan21 release process).
It looks like I fixed it (to be honest it was not an easy one for me) but it would be nice if you could comment.
> (fix) prompt in qtspock when used with new traitlets

- src/sardana/taurus/qt/qtgui/extra_sardana/test/test_qtspock.py
On Windows it was observed that the qtspock tests that
have timeout set to 5 s sporadically fail.
The ones with the timeout set to 10 s works well.
This happened only when executed within the testsuite,
when executed separately it was not observed.
As an immediate solution, unify all timeouts in all tests
to 10 s.
@schooft hope you don't mind this change. For me, it was easier like this to have a reliable testsuite on Windows. I will auto-merge whenever the CI on Linux turns green but feel free to leave comments here.
> (test) increase timeout for qtspock tests

- setup.py
During the Jan21 release it was observed that the Sardana GUIs launchers,
when sardana is installed on Windows with pip, does not launch
the applications at all.
In the previous releases Sardana was never tested on Windows when installing with
pip, but with MSI, and in this case the launchers were working correctly.
Since version Jan21, the recommendation is to use Sardana on Windows with pip.
In order to overcome this problem change the GUIs launchers from gui_script to
console_scripts entry points. Similar solution was already applied for Taurus
in taurus-org/taurus#541.
> (fix) sardana GUIs launchers on Windows

- src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py
In the PMTV widget, one can introduce negative values in the relative move write
widget. It is ambiguous since the relative movement is commanded with a move negative
or move positive buttons - there is no need to add a sign to the delta displacement.
Set bottom limit to 0 for the validator. `sys.float_info.min` was also evaluated but it
still allows moving the motor with 0 delta.
Fixes #1571.
> (fix) make PMTV relative move combobox accept only positive numbers

- src/sardana/macroserver/scan/gscan.py
Today @tiagocoutinho reported that scans, when get stopped, stop all the instruments present in the Pool. Then in the Spock we could see something like this:
```
Stopping /monitor reserved by dscanc
Stopping /mirror reserved by dscanc
Stopping /slit reserved by dscanc
```
GScan reserve instruments for the scanning macro when it simply
looks for the instruments information e.g. full names. This makes
the MacroExecutor to stop the instruments when the macro is
being stopped as it would do with any other reserved object.
Do not reserve instruments cause it does not make sense to stop
them when stopping the macro.
> fix: do not reserve instruments in GScan

- setup.py
#724, #540 requires taurus >= 4.7.1
#1077, #540 requires taurus >= 4.7.1.1
Tested:
- on Linux, installing with pip (in a conda environment) where taurus 4.7.0 was available and pip considered this version as satisfactory
- on Windows, installing with pip (on Python installed with the exe installer from python.org) where taurus 4.7.0 was available and pip considered this version as **not satisfactory** and performed the upgrade
> bump taurus requirement to >= 4.7.1.1 on windows

- CHANGELOG.md
- doc/source/devel/howto_controllers/howto_1dcontroller.rst
- doc/source/docs.rst
- doc/source/news.rst
- doc/source/users/faq.rst
- doc/source/users/spock.rst
- doc/source/users/taurus/poolchanneltv.rst
- doc/source/users/taurus/poolmotortv.rst
- doc/source/users/taurus/showscan.rst
The need for this section was identified in https://github.com/sardana-org/sardana-followup/issues/32.
The format was not decided at that time. The last release provided it in the [GitHub release description](https://github.com/sardana-org/sardana/releases/tag/3.0.3). This time I tried another approach and add it to the docs directly.
IMHO it is better cause it unifies the news with the docs making them easier to discover.
Here is how it looks:
> Add "What's new?" section to docs

- src/sardana/taurus/core/tango/sardana/pool.py
Operations, like for example motion or acquisition, are attempted to start
even if the element is already Moving. Early recognize this situation
on the client and raise an exception before requesting start to the server.
**Dependencies:**
- #1591
- [taurus-org/taurus!1191](https://gitlab.com/taurus-org/taurus/-/merge_requests/1191)
I have tested it with the following _buggy_ dummy counter/timer:
```diff
diff --git a/src/sardana/pool/poolcontrollers/DummyCounterTimerController.py b/src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
index eab5cf141..28b8e3284 100644
--- a/src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
+++ b/src/sardana/pool/poolcontrollers/DummyCounterTimerController.py
@@ -79,6 +79,7 @@ class …
```
> Do not try to start operation when state is Moving

- setup.py
- src/sardana/taurus/core/tango/sardana/macroserver.py
- src/sardana/taurus/core/tango/sardana/pool.py
`AttributeEventWait.waitEvent()` use non-intuitive API and showed to be buggy - see [taurus-org/taurus#573](https://gitlab.com/taurus-org/taurus/-/issues/573) and
[taurus-org/taurus!1191](https://gitlab.com/taurus-org/taurus/-/merge_requests/1191).
Use an improved method `AttributeEventWait.waitForEvent()`.
Bump taurus version requirement.
Note, this PR is urgent to be reviewed and eventually merged since after the premature merge of https://github.com/sardana-org/sardana/pull/1592 currently the develop branch is in a broken state.
> Use AttributeEventWait.waitForEvent() instead of deprecated AttributeEventWait.waitEvent()

- src/sardana/taurus/core/tango/sardana/pool.py
PoolElement can can try to start when its state is different than
Moving. This tries to start elements in Fault state as well
what can hang the server, for example, in the case of
the measurement group. See discussion in #1316. Allow to start
the PoolElement only if it is in On or Alarm state.
> Allow to start PoolElement only when it is in On or Alarm states

- src/sardana/macroserver/macros/standard.py
Independent acquisition of experimental channels done with `ct`
macro can not be stopped/aborted. This is because the channel is
not reserved by the macro. Reserver it by using `Macro.getObj()`
call.
> Fix stop/abort element in ct macro when used with channels

- .bumpversion.cfg
- CHANGELOG.md
- doc/source/news.rst
- src/sardana/macroserver/msmacromanager.py
- src/sardana/release.py
- src/sardana/tango/macroserver/Door.py
#1559 introduced a bug which does not allow to abort macros executing hooked macros. This is because a dedicated `_macro_pointer` is being wrongly invalidated at the end of the `runMacro()` method.
Refactor the concept of _macro_pointer_ - use a property which points to the macro at the `_macro_stack`. This avoids the problem of having to update the `_macro_pointer`.
Deprecate `clearRunningMacro()` in favor of `clearMacroStack()`.
Fixes #1603.
@HEnquist, @13bscsaamjad could you please review and test it? I put a release date for tomorrow. If you merge on another day, before the merge, please update the date of the release in the "What's new?" and in the CHANGELOG.md. Finally, please also continue the [hotfix release process](https://github.com/sardana-org/sardana/wiki/How-to-Hotfix-Sardana …
> Hotfix 3.1.1: allow to stop/abort macro executing another hooked macro

- src/sardana/tango/pool/MeasurementGroup.py
MeasurementGroup's persistent information about elements is stored in two places:
1. Elements property
2. Configuration memorized attribute
The first one is set only once, at the MeasurementGroup creation time. The subsequent
changes of the configuration does not update the Elements property. Update it on the
successful write of the Configurtion attribute in order to maintain them in sync.
> Update MeasurementGroup's Elements property when Configuration attr is written

- src/sardana/macroserver/scan/gscan.py
post-scan hook is only executed in case of normal end of the scan.
In some case it will be convenient to execute it also in case the
scan failed or was stopped/aborted. The hook could identify
the scan endstatus from its environment.
> Execute post-scan also in case of an exception

- src/sardana/taurus/core/tango/sardana/pool.py
As said on the last follow-up meeting I recovered on old work (still done together with @amilan many years ago) and tried it again. Indeed with Tango 9 it works like a charm and looks like fixes the said bug. Details below:
MeasurementGroup _proxy_ object resides on the client side after removing it on the server. This leads to inconsistency when one recreates the measurement group using the same name e.g. its list of the channels corresponds to the list of the channels of the previously deleted measurement group.
Explicitly remove the Taurus objects (device and its attributes) from the factory so they do not interfere with the future attempts to recreate objects with the same name.
These are the circular references that I tracked and are explained in the inline comment:
Fixes #145, …
> Fix: completely clean client side after removing a measurement group

- doc/source/users/spock.rst
I fixed a small typo on [Spock's docs](https://sardana-controls.org/users/spock.html#executing-macros) where it says to use `lsmac` but then `lsdef`:
I replaced `lsmac` with `lsdef` and added a small suggestion:
👍🏻
> [docs] Small fix on spock's `lsmac`/`lsdef` usage 

- src/sardana/spock/inputhandler.py
- src/sardana/spock/ipython_01_00/genutils.py
When macro input gives timeout then the Spock (IPython) gets hung completely.
It seems to be a bug in IPython - see https://github.com/ipython/ipython/issues/12078.
Use [`prompt_toolkit.prompt()`](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#prompt_toolkit.shortcuts.prompt) (a dependency of IPython) instead of `input()` and raise an exception in the thread waiting for input when the timeout was reached. This apparently works while `input()` does not react on exceptions sent in this way.
Also change the message in Spock when the timeout is reached so it appears this way:
```
Door/zreszela/1 [3]: question
Answer (y/n) [y] Input timeout reached!
User answered: y
```
instead of:
```
Door/zreszela/1 [4]: question
Answer (y/n) [y] SpockInputHandler input timeout …
```
> fix: hang of IPython when macro input gives timeout

- .devcontainer/.env
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/sardana_dev/Dockerfile
- .devcontainer/sardana_dev/environment.yml
- .vscode/settings.json
This adds a docker-compose with four containers, one for the Sardana development with a clean conda environment specified in the file environment.yml and the other 3 related to have a Tango CS (tangodb, databaseds and tangotest).
By default the TANGO_HOST is set to databaseds:10000 but an external Tango DB could be used.
> Add devcontainer for VS Code - Remote Containers

- doc/source/users/configuration/macroserver.rst
- src/sardana/tango/core/util.py
- src/sardana/tango/macroserver/MacroServer.py
rfoo is not available for Python 3. Remove its usage from sardana.
Relates to #1117
> fix: remove rfoo (rconsole) usage in sardana and in docs

- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/tango/pool/MeasurementGroup.py
#867 accidentally introduced backward-incompatible changes
which break the measurement groups which external controllers e.g. Tango
have synchronizer/timer/monitor configured. Relax validation and print
a deprecation warning instead of raising an exception.
This was discovered at ALBA by @jairomoldes and @tiagocoutinho. @jordiandreu could you test if it avoids the problem?
I would expect that with this change, if you read the configuration back, the synchronizer/timer/monitor parameters should not be there anymore, could you check this as well, please?
> fix: provide back compat for external ctrls meas conf

- src/sardana/pool/poolmotor.py
Since Tango version 8 the memorized attributes lost the history of
changes and is not possible to easily track changes.
Add log messages to offset, sign and step_per_unit
attributes to facilitate tracking over changes.
fixes #1508
> feat: add history log message for motor attributes

- src/sardana/spock/ipython_01_00/genutils.py
- src/sardana/tango/pool/test/base_sartest.py
taurus for many years was allowing to retrieve its version from the
taurus.core.release module directly, even if this was not a recommended way.
taurus!1199 does not allow it anymore.
Change the way of obtaining the version number. In the future it will be
possible to use `taurus.__version__` directly.
> fix: correctly extract taurus version

- src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/sequenceeditor.py
Fixes #305 
Couple action buttons bug fixes:
- When a macro is added to the sequence, now the "New sequence"  button remains enabled.
- When no macros remain in the sequence tree after deleting them, the "Save sequence" and "Play sequence" buttons now remain disabled,
- When new sequence is created "new sequence" remain enabled and "play" button remain disabled
> Sequencer action buttons

- src/sardana/macroserver/macroserver.py
This suggestion comes from Manu Taurel from ESRF.
Tango commands: ReloadMacro and ReloadMacroLib does not report problems with reloading macros or macro libraries. If the module being reloaded contains bugs it gets silently "reloaded". Maybe raising an exception could a good way of communicating it?
Reported by: reszelaz ( http://sf.net/u/zreszela )
Original Ticket: sardana/tickets/118
Fix: #75 
-----------------------------
Description of the argout says: "[OK] if successfull or a traceback if there was a error (one string with complete traceback of each error". However even if the error occurs the [OK] string is returned.
Reported by: reszelaz ( http://sf.net/u/zreszela )
Original Ticket: sardana/tickets/119
Fix: #76
> raise exception in relmaclib and relmac methods if any is detected

- src/sardana/macroserver/macros/scan.py
- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/macroserver/recorders/output.py
- src/sardana/macroserver/scan/gscan.py
This is an updated more elaborate version of https://github.com/sardana-org/sardana/pull/1632. It fixes https://github.com/sardana-org/sardana/issues/1321
After a scan, it reports the setup part of the deadtime (snapshots etc) separately like this:
```
Door_dummy_1 [5]: ascan mot01 0 1 4 0.1
Operation will be saved in /tmp/dummmy2.h5 (HDF5::NXscan from NXscanH5_FileRecorder)
Scan #24 started at Thu Jul  8 08:38:42 2021. It will take at least 0:00:01.348528
#Pt No    mot01      ct01      ct02       dt   
0         0        0.1       0.2     0.34582 
1        0.25      0.1       0.2     0.660809
2        0.5       0.1       0.2     0.969109
3        0.75      0.1       0.2     1.28313 
4         1        0.1       0.2      1.5818 
Operation saved in /tmp/dummmy2.h5 (HDF5::NXscan)
Scan #24 …
```
> Issue1321 scan start time taken too late, take 2

- src/sardana/macroserver/scan/gscan.py
This pull request fixes #1321 
The fix is to take the start time already when creating the scan object, and not when starting the scan loop (after potentially slow things like taking snapshots).
> Take scan starttime before snapshots

- src/sardana/macroserver/recorders/output.py
- src/sardana/macroserver/scan/gscan.py
Adds a table with some helpful output of the motor settings that are about to be used in a continuous scan. 
In order to implement this, we had to change how the header of the scan table is output; it is now printed when the first point arrives, and not immediately. This also prevents some issues with info/debug messages appearing after the header.
The original issue #692 also suggests showing the restored settings after the scan but for similar reasons (see issue #1651) it is currently commented out. It can be added in whenever that issue is solved.
Example:
```
Door_2_1 [5]: ascanct mot10  0 10 10 0.1 0.1
ScanDir is not defined. This operation will not be stored persistently. Use "expconf" or "newfile" to configure data storage (or eventually "senv ScanDir <abs directory>")
Scan #31 …
```
> Add ascanct parameter output

- src/sardana/taurus/core/tango/sardana/pool.py
Different types of exceptions are not possible here so there is no need for the control_exceptions argument to Taurus' waitforEvent. Ref to [PR](https://gitlab.com/taurus-org/taurus/-/merge_requests/1204) in Taurus. Reverting here as well.
> revert control_exceptions arg to waitForEvent

- src/sardana/macroserver/recorders/h5storage.py
- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
- Nexus recorder: handle duplicated snapshot labels 
- Do not allow setting duplicated snapshots in Exponf 
Fixes #87 
(worked with @emiliojmorales )
> Fix #87  (error with duplicated pre-scan snapshots)

- src/sardana/macroserver/macros/expert.py
- src/sardana/tango/pool/Pool.py
This PR avoid errors coming up when running edctrlcls and edctrllib macros. The macros are still not
functional, since they have to be moved to magic commands (like edmac and edmaclib is done), but
this PR solves bugs in the code of the macros and of the sardana core. Now the code is ready for
further implementation (not done now since it has very low priority and it has to be discussed if it
is worth to implement it). Issue #317 is closed with this PR.
> Avoid errors in edctrlcls and edctrllib macros

- src/sardana/pool/pool.py
- src/sardana/sardanacustomsettings.py
- src/sardana/tango/core/util.py
Currently the log files size and number of backups used by loggers in sardana (e.g. by Pool and MacroServer DSs) is hardcoded to 10M and 5 respectively. Make this a variable that can be controlled via sardanacustomsettings.py.
Fix: #141
> Allow user to control MS and pool log files size & number

- src/sardana/spock/ipython_01_00/genutils.py
It is not possible to distinguish in Spock if the Door (MacroServer server) is running.
Previous genutilis (IPython 0.10) offered this information.
Fix it for IPython >= 5 by appending "(OFFLINE)" suffix to the prompt.
Fixes #1621.
This is what I get now when the Door is offline on the Spock startup:
```
╰─>$ spock
MainThread     INFO     2021-07-01 00:13:09,032 TaurusRootLogger: Using PyQt5 (v5.12.3 with Qt 5.12.9 and Python 3.9.1)
MainThread     WARNING  2021-07-01 00:13:09,246 TaurusRootLogger: epics scheme not available: ModuleNotFoundError("No module named 'epics'")
[TerminalIPythonApp] WARNING | Config option `deep_reload` not recognized by `TerminalInteractiveShell`.
Spock 3.1.2-alpha -- An interactive laboratory application.
help      -> Spock's help system.
object?   -> Details …
```
> fix: spock prompt informs when the Door is offline

- src/sardana/macroserver/msmacromanager.py
- src/sardana/taurus/core/tango/sardana/motion.py
https://github.com/sardana-org/sardana/issues/1578#issue-876870113 explains a failed attempt to implement an equality check on the `Motion` class in order to avoid reserving different `Motion` objects pointing to the same moveables multiple times:
>  I tried to Implement the `__eq__()` method in the `Motion` class so we could discover _duplicates_ in https://github.com/sardana-org/sardana/blob/74f3e1ad46b19665c8d206782c19e02fdaf76ba9/src/sardana/macroserver/msmacromanager.py#L1820 but this does not help. This is because, in other places in the code, we assume that this class is hashable e.g. we use its objects as keys in the dictionaries.
It appeared that the said dict is not used anywhere in the code. In order to fix #1578 I propose to remove this dict in 9595940 and then implement the …
> Stop motion only once in scans

- src/sardana/macroserver/macros/test/test_scanct.py
- src/sardana/pool/pool.py
- src/sardana/pool/poolacquisition.py
- src/sardana/pool/poolbasechannel.py
- src/sardana/pool/poolbaseelement.py
- src/sardana/pool/poolcontroller.py
- src/sardana/pool/poolelement.py
- src/sardana/pool/poolmeasurementgroup.py
- src/sardana/sardanaevent.py
- src/sardana/tango/pool/Controller.py
- src/sardana/tango/pool/MeasurementGroup.py
- src/sardana/tango/pool/MotorGroup.py
- src/sardana/tango/pool/Pool.py
- src/sardana/tango/pool/PseudoCounter.py
- src/sardana/tango/pool/PseudoMotor.py
- src/sardana/tango/pool/test/base_sartest.py
- src/sardana/taurus/core/tango/sardana/pool.py
This pull request resolves #1586. Now a check for dependent elements is performed when an element is going to be undefined. 
So far we tested it for Pseudocounters, Motorgroups, Pseudomotors and, Measurement Groups.
The remaining tests could be testing for Pseudomotors that have as dependent elements another Pseudomotors.
----
IMPORTANT: This PR introduces usage of `gc.collect()` in Sardana. cycle-reference may exist between an element and a traceback stored in `SardanaValue` or `SardanaAttribute` as a consequence of getting `sys.exc_info()` and storing a reference to it. Since _dependent elements_ are determined by introspecting the listeners we need to attempt garbage collection of these cycled-referenced objects.
> Udef checks dependencies

- src/sardana/tango/pool/ZeroDExpChannel.py
0D Tango implementation only consider some attributes events e.g. value, valuebuffer, etc.
Consider other attributes' events e.g. shape.
Fixes #1618.
@dschick could you please test it? Many thanks!
Reading the shape attribute still gives None. The same is for counter/timer channels. But I think this is how PyTango deals with empty spectrums: https://gitlab.com/tango-controls/pytango/-/issues/271.
> fix: consider events from not standard 0D channel attributes

- src/sardana/sardanamodulemanager.py
When loading a module that internally imports some libraries (i. e. clr of Python.NET) Python is unable to import the module using `__import__` but it works when using **importlib**. The documentation of `__import__` recommends using importlib outside of the interpreter.
> fix Python import error of sardana module using clr of Python.NET

- src/sardana/macroserver/recorders/h5storage.py
h5 recorder creates hard reference to macro object in _startRecordList()
method. This closes the cycle reference between macro, GScan and recorder
since GScan has hard references to the recorders and macro has hard
references to the GScan.
Use weakref instead of hard references between recorder and macro.
This trend shows how memory stays stable during 10 scans with 2d channels
@dschick @felix92 
This PR should fix the issue you reported in https://github.com/sardana-org/sardana/issues/1095#issuecomment-875706639
> Fix: Avoid cycle reference between h5 recorder and macro

- src/sardana/taurus/core/tango/sardana/macroserver.py
(Related to https://github.com/sardana-org/sardana/issues/1665)
This PR remove an unnecessary property overwrite. It's unnecessary because it already assigns a value in the constructor:https://github.com/sardana-org/sardana/blob/3eb154ccc4b25001925c4a48ce060d7cfda7e496/src/sardana/taurus/core/tango/sardana/macroserver.py#L337
So, it makes it impossible to make a custom output. The solution is just to remove the line.
😄 Thanks
> Fix: Remove unnecessary property overwrite

- src/sardana/pool/poolmeasurementgroup.py
#867 introduced backward compatibility layer for measurement group
configurations with non-referable channels containing value_ref_*
parameters. This compatibility layer assumes that in this case both
parameters: value_ref_enabled and value_ref_pattern are present, which is
not always true.
Fix it by considering also the case when only one of these parameters is
present.
@ByRellex could you please confirm this fixes the issue you have discovered? As soon as you confirm and the CI is green I will auto-merge. Thanks!
> fix: backward compatibility for meas grp conf value_ref_*

- src/sardana/macroserver/macros/scan.py
The current amultiscan macro does not work due to a problem with the input parameters.
This PR solve it, perhaps not in a very elegant way, but we needed a solution urgently.
> Solving amultiscan arguments error

- .bumpversion.cfg
- CHANGELOG.md
- doc/source/news.rst
- src/sardana/macroserver/macros/scan.py
- src/sardana/macroserver/scan/gscan.py
- src/sardana/release.py
#1095 documents MacroServer memory growing problems when performing numerous long scans. The last investigation [demonstrated a significant improvement when using jemalloc](https://github.com/sardana-org/sardana/issues/1095#issuecomment-596144102). Those tests were done on timescan, and I assumed that the continuous scans should behave the same since these scans reuse the same implementation of the data handling. But this assumption turned out to be wrong, as demonstrated in this trends:
(All examples in this description use measurement group with 20 software synchronized dummy counter/timers)
- `repeat 10 "ascanct mot01 0 100 10000 0.001"`  - increas of 260 MB!
- `repeat 10 "meshct mot01 0 50 5000 mot02 0 1 1 0.001"` - increase of 260 MB 
This PR provides a hotfix release 3.1.2 which …
> Hotfix 3.1.2 - fix memory leak in continuous scans

- src/sardana/macroserver/scan/gscan.py
8815c91 introduced a hack to avoid recursive decrease of
velocity in continuous scans. Most probably this hack was needed
to avoid some synchronization problems between the software
continuous scan threads (motion and acquisition are done in
separate threads).
When using Taurus 4 this hack is not applied
cause the attribute's range returns -inf and inf floats
instead of "Not specified" string and we don't fall into the
except clause anymore.
Refactor the `CScan.get_max_top_velocity()` to consider only
Taurus 4 and above case (we don't support Taurus < 4 anymore)
and maintain the hack.
Also, log failed setting of maximum top velocity in continuous scans.
Fixes #1574.
> Fix restoring velocity in software (ascanc) continuous scans

- src/sardana/taurus/qt/qtgui/extra_sardana/expdescription.py
Since [taurus MR !1213](https://gitlab.com/taurus-org/taurus/-/merge_requests/1213) , launching expconf triggers a warning in taurus due to `QCoreApplication` being already instantiated when attempting to import `QtWebEngineWidgets`. Avoid it by doing an early import of `QtWebEngineWidgets` in `expdescription.py`
> Avoid QtWebEngineWidgets-related warning from taurus
