src/sardana/macroserver/recorders/storage.py

Implement the code to save the OneD channels on spec file

Feature 360

---

src/sardana/macroserver/macros/test/test_expert.py
src/sardana/pool/pool.py
src/sardana/pool/poolcontroller.py

This PR resolves issue 316 and adds unittest of renameelem macro.

Issue 316 - rename pool's element

---

CHANGELOG.md
MANIFEST.in

Add CHANGELOG file in Sardana documenting the major changes
between versions.

Add CHANGELOG in Sardana

---

src/sardana/tools/config/README.md
src/sardana/tools/config/get_pool_config.py
src/sardana/tools/config/sardana.py
src/sardana/tools/config/template.fods

get_pool_config.py script was updated to be able to dump the current Pools (originally it was written to
dump Pools written in C++). Apart of that:
* a basic documentation was added in form of the README file.
* template FODS file was added
* simple improvements were added to sardana.py script
@amilan could you take care about the review and integration, please?

Updated config tools

---

src/sardana/macroserver/macros/examples/parameters.py
src/sardana/macroserver/msmacromanager.py
src/sardana/macroserver/msparameter.py
src/sardana/spock/parser.py
src/sardana/spock/spockms.py
src/sardana/spock/test/test_parser.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/macroparameterseditor.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroparameterseditor/model.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/sequenceeditor/model.py

Add option for node duplication in macroexecutor (issue 426).
Add button in macroexecutor for allowing RepeatNode duplication.

Add option for node duplication in macroexecutor (issue 426)

---

src/sardana/macroserver/recorders/storage.py

Changes only affecting the data format used at DESY. 
It is harmless to merge it to the develop branch.

Forcing readout from hw

---

src/sardana/macroserver/macros/hkl.py

A new try solving the pep8 problems. Many thanks @reszelaz and @cpascual for your help.

Adapting hkl macros to 4 circle diffractometers

---

.travis.yml
CONTRIBUTING.md
ci/flake8_diff.sh

This PR aims to improve the output of the flake8 check in travis-ci - #452.

Improve flake8 output in travis-ci (#452)

---

CHANGELOG.md
src/sardana/macroserver/scan/gscan.py

Hi Jan, this is only a first try. Could you test if the files are correctly close with this change?.
Thanks.

Solve issue-455: close file on stopping the scan

---

.bumpversion.cfg
CHANGELOG.md
src/sardana/macroserver/recorders/h5storage.py
src/sardana/macroserver/scan/recorder/storage.py
src/sardana/release.py

Adapt the solution to #460 to develop. The solution was implemented for fixing https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861900 . 
Fixes #460

Fix #460 Use h5py insted of nxs in Sardana

---

src/sardana/macroserver/macros/ioregister.py
src/sardana/pool/controller.py
src/sardana/tango/pool/IORegister.py
src/sardana/tango/pool/Pool.py

This is a possible solution for the bug.

Issue #458: IORegisterController WriteOne method gives a integer as value

---

src/sardana/macroserver/msmacromanager.py
src/sardana/macroserver/msrecordermanager.py
src/sardana/tango/macroserver/Door.py
src/sardana/tango/macroserver/MacroServer.py

This PR  solves the MacroServer issues when it exits after a Ctrl+C
Fix #494 
Some taurus issues has been reported:
- https://github.com/taurus-org/taurus/issues/511
- https://github.com/taurus-org/taurus/issues/512

Fix MacroServer does not exit smoothly after Ctrl+C

---

doc/source/devel/howto_controllers/howto_controller.rst

Add TriggerGateController to the available controllers

Update howto_controllers doc

---

src/sardana/macroserver/recorders/examples/dummy.py
src/sardana/macroserver/scan/recorder/datarecorder.py

Fix DumbRecorder.
- DataRecorder class constructor needs and extra argument. Add it.
- Fix DumbRecorder without using 'time' library.

Fix DumbRecorder

---

src/sardana/tango/core/SardanaDevice.py

Add verbosity to warning message about the w_value out of range.

Add verbosity to warning message

---

src/sardana/pool/poolpseudomotor.py
src/sardana/pool/test/base.py
src/sardana/pool/test/fake.py
src/sardana/pool/test/helper.py

This PR adds some helpers useful in testing pseudo motors.

Add pseudo motor testing helpers

---

src/sardana/macroserver/scan/gscan.py

Theoretical positions are not correclty calculated. Fix it by changing the number of numpy.linspace argument.

Fix bug in theoretical position in ascanct & co.

---

doc/source/devel/api/tango_device_pool.rst
src/sardana/tango/pool/Motor.py

Fix the reference of tango motor property "Sleep_bef_last_read".
It is bad writen in the sardana documentation.
Replace Sleep_before_last_read by Sleep_bef_last_read

Fix documentation

---

src/sardana/macroserver/scan/gscan.py
src/sardana/pool/poolelement.py
src/sardana/pool/poolmeasurementgroup.py

This PR solves #122 and substitutes PR #612. More information in the said PR.

Fix taurusgui with instruments (instead of #612)

---

src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/favouriteseditor.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/favouriteseditor/historyviewer.py

Some icons are not visible in macroexecutor.
Use QIcon.fromTheme in order to load the icons correctly.

Use QIcon.fromTheme to get the Icons

---

src/sardana/macroserver/macros/expert.py

Add relctrl macro

---

src/sardana/macroserver/macros/standard.py
src/sardana/taurus/core/tango/sardana/pool.py

Fix uct macro

---

src/sardana/tango/macroserver/Door.py

Allow to stop a Macro (by aborting it) when this macro is paused.

Allow to stop a Macro when it is paused

---

src/sardana/pool/poolacquisition.py

Additional protection to Pull Request [#614)[https://github.com/sardana-org/sardana/pull/614]
On find the master timer, it should to take into account that the element must be enabled.

On find master, check if the timer enabled

---

src/sardana/macroserver/scan/scandata.py

Allow to get the data from the record as a dictionary. It is possible to give the alias of the channel.

Add __getitem__ method to Record class

---

src/sardana/pool/poolutil.py

It fixes point 3) mentioned in #662

add lock to PoolUtil

---

src/sardana/macroserver/msmacromanager.py
src/sardana/macroserver/msmetamacro.py

Report error message in spock if macros cannot be reloaded

Report error message if macros cannot be reloaded

---

src/sardana/macroserver/macros/scan.py
src/sardana/macroserver/scan/gscan.py
src/sardana/util/motion/motion.py

Adapt the CT Scan class to implement multiple waypoints and implement the meshct macro

Meshct macro

---

src/sardana/macroserver/macros/standard.py

src/sardana/macroserver/macros/standard.py flake8 corrections

flake8 corrections

---

src/sardana/pool/poolcontrollers/HklPseudoMotorController.py

Hi, I have added the DiffractometerType to the file saved with the SaveCrystal command.
Our main users of the diffractometer in sardana need this information in the file.

Adding DiffractometerType to crystal file

---

src/sardana/macroserver/macros/scan.py

Create a dscanct version of ascanct

Add dscanct macro

---

src/sardana/macroserver/macros/scan.py

Applied the solution of the PR #683 to the other scan macros

Fix getData error.

---

src/sardana/pool/poolcontroller.py

Remove unused methods stop_axes and abort_axes

Remove unused methods

---

src/sardana/macroserver/macros/standard.py

Provide Record data to uct macro

---

src/sardana/pool/poolpseudomotor.py

This is a reduced version of #663 intended to be included in Jan18 release.

Protect limits of physical motors when moving pseudo motors

---

doc/how_to_release.md

Change to demo2

---

doc/how_to_release.md

Detail description for counter plot output

Detail description for counter plot output

---

doc/source/devel/howto_controllers/howto_triggergatecontroller.rst

Remove non-correct bracket

---

src/sardana/macroserver/macros/standard.py

Add repeat macro (from third-party repository:
https://sourceforge.net/p/sardana/macros.git/ci/master/tree/ALBA_GENERAL/tools.py).
Fix issue-308.
Just after integrating it we should add a comment in the third-party repo that this was moved to the standar macros.
@dschick could you test it?

Add repeat macro to standard macros

---

src/sardana/pool/poolcontrollers/HklPseudoMotorController.py

Set selected_trajectory to the maximum possible value if the selected one is out of range.

Avoid error if selected_trajectory does not exist

---

doc/source/index.rst

This commit adds the Sardana Wiki link to the sidebar.

Add the Sardana Wiki.

---

doc/source/users/scan.rst

I don't really know if this is everything one should know about the snapshots.

Add documentation for scan snapshots

---

doc/source/devel/howto_controllers/howto_pseudomotorcontroller.rst

This commit adds the documentation about how to create pseudo motors.

[WIP] Add how to pseudomotors

---

src/sardana/taurus/core/tango/sardana/pool.py

Fix two methods in Controller taurus extension:
* `getElementByAxis`
* `getElementByName`

Fix Controller taurus extension

---

doc/source/users/configuration/index.rst
doc/source/users/configuration/server.rst
doc/source/users/getting_started/running_server.rst
src/sardana/tango/core/util.py

Allow to configure the ORBendPoint omniORB parameter from tango DB free properties. 
The priority order is:
1. Arguments
2. Environment Variable
3. Tango DB free property

Configure ORBendpoint omniORB argument from free properties

---

src/sardana/macroserver/macros/scan.py
src/sardana/macroserver/scan/gscan.py

Add _pre-acq_ and _post-acq_ hooks to aNscanct macro.

Acquisition hooks

---

doc/source/users/index.rst
doc/source/users/macro_logging_and_reports.rst
src/sardana/sardanacustomsettings.py

Corrected the comments from PR #878

Docu: Macro Logging and Reports

---

doc/source/devel/overview/index.rst
doc/source/devel/overview/overview_instrument.rst

@reszelaz, i am sorry, I do not find in the documentation de [Howto-GUI_creation] where you
said that the configuration of the instruments is described. This part is missed in the PR, if you
tell me where to find it (for using a link to that) I will add it. Thanks.

Docu: Instrument

---

src/sardana/macroserver/macro.py

Can not stop programmatic hooks

---

src/sardana/macroserver/macro.py

#810 actually has side effects on aborting macros. This was revealed in https://github.com/sardana-org/sardana/issues/900#issue-348659916:
>**Warning:** After previously aborting `umvr` macro and then running the scan the outputs of the `umvr` were still appearing mixed with the scan output, see [output](https://gist.github.com/reszelaz/e13203accad25dd3bb1670b5f37641ce).
Quickly investigating seems like the `StopException` being raised from the `Macro.outputBlock` is catched by the thread executing the position update callback. This then does not allow executing the `umv._cleanup` code responsible for removing the position update callbakc.
Initially I was suspecting that [taurus-org/taurus#738](https://github.com/taurus-org/taurus/pull/738) could have affected that. But it has nothing to …

Revert "Can not stop programmatic hooks"

---

src/sardana/pool/poolcontrollers/HklPseudoMotorController.py

This PR adapt the hkl controller for accepting two new diffractometer types.

Adding diffractometer types

---

src/sardana/macroserver/macros/hkl.py

After testing with a new beamline for a new diffractometer type, we need to adapt the hkl macros.

Adapting for 4c diffrac

---

src/sardana/macroserver/scan/gscan.py

pre-scan and post-scan hooks are executed within the scan_loop. Before
the scan loop, for example, are started the scan recorders making
them to start the scan entry. It makes more sense to not start them
until the pre-scan hooks are executed - they may want discard the scan
or simply may not want to mix the scan header output with the pre-scan
hooks output.
This solution allows to avoid the code duplication in all the scan
specific implementation.

Move pre-scan and post-scan hooks out of scan_loop (issue-920; previously pr-922)

---

doc/source/devel/howto_macros/macros_general.rst
src/sardana/macroserver/macro.py
src/sardana/macroserver/msparameter.py
src/sardana/taurus/core/tango/sardana/macro.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py

Implement optional parameter for the macros. Adds #285.

Optional param

---

src/sardana/macroserver/macros/standard.py

Add measurement group as a optional parameter using the Option parameter feature

Provide MeasurementGrp as a parameter in ct macro

---

src/sardana/taurus/core/tango/sardana/motion.py

Centralizing duplicated conditional loop.

Flyingbot centralize pytango devstate retrieval

---

src/sardana/spock/ipython_01_00/genutils.py

Fixes #971 
@sardana-org/integrators it is ready for review. Thanks!

 Do cleanup when spock profile was not correctly created

---

sardanaConfig/src/wizards/pool_page.py

When `len(sys.argv) > 1` the second condition is never met

Flyingbot bugfix pool page

---

src/sardana/pool/poolmetacontroller.py

The `Description` is an optional parameter.  https://sardana-controls.org/devel/howto_controllers/howto_controller.html

Fix bug on controller description reading

---

src/sardana/macroserver/macros/examples/acquisition.py
src/sardana/taurus/core/tango/sardana/pool.py

This examples are more or less the demos of the independent acquisition of the experimental channel feature that we did on today's follow-up meeting. I thought it would be interesting to have them in the macro example *catalogue*.

Acq acquisition macro example

---

src/sardana/taurus/core/tango/sardana/pool.py

I should fix one of the reason of sardana hanging #1023. 
I replaces `deepcopy` of `DeviceProxy` by a simple reference copy.

avoid deepcopy of DeviceProxy

---

src/sardana/macroserver/recorders/storage.py

* removes circular dependencies of macro object related to FIO recorder 
* applies the new naming scheme (with tango://) for MCAs in FIO recordder

fix for FIO recorder

---

doc/source/devel/howto_macros/macros_general.rst

Add macro simultaneous actions description and examples

---

src/sardana/spock/spockms.py

Allow to open only h5 files and add logic to find it if the ScanFile is a list. 
See #1055 comments.

Add protection to showscan

---

README.md

So you can see a description of the project on Github.

Add basic Readme file

---

src/sardana/macroserver/macro.py

Seems that macro function environment and hints are swapped.
This PR fixes that

Fix macro function environment and hints

---

src/sardana/macroserver/scan/gscan.py

advertise newfile macro in case no ScanDir or ScanFile is set

---

src/sardana/macroserver/msmacromanager.py
src/sardana/macroserver/msrecordermanager.py
src/sardana/macroserver/scan/gscan.py
src/sardana/pool/poolaction.py
src/sardana/pool/poolcontrollermanager.py
src/sardana/sardanabuffer.py

Remove unused imports of ordereddict for python ver < 2.7

Remove unused imports of ordereddict for python ver < 2.7

---

src/sardana/taurus/core/tango/sardana/macroserver.py

Reverts sardana-org/sardana#1245

Revert "Console size py3"

---

src/sardana/pool/pool.py
src/sardana/pool/poolmeasurementgroup.py

Allow measurement groups renaming

---

doc/source/devel/howto_recorders.rst
doc/source/glossary.rst
doc/source/users/configuration/macroserver.rst
src/sardana/sardanacustomsettings.py

We had it on the todo list, but since #1274 raises a question about that I prefered to add already something to the docs. Yes, it is very minimal infomration, but may be already usefull. @sardana-org/integrators could you check that? Also @stanislaw55 it would be great if you could review it and comment (or maybe even complete:)) based on your experience in wrting recorders...
Thanks to all!

Add basic information to "how to write custom recorder" docs

---

src/sardana/taurus/qt/qtgui/extra_pool/poolmotor.py

New feature that saves motor expert view and write widged on perspective and LAST settings.
Fixes #277

New feature to save motor expert view and read widged

---

setup.py
src/sardana/taurus/qt/qtgui/extra_sardana/showscanonline.py
src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py

* multiple plots in the same MultiPlot widget (as opposed to different panels before)
* option to group curves by x-axis or individual plot per curve
* add showscan console script
* support fast scans: update curves at a fix rate (5Hz)
* better curve colors and symbols

showscan improvements

---

src/sardana/tango/core/SardanaDevice.py
src/sardana/tango/pool/Pool.py

Make sure sardana tango servers always use the latest tango API

Fix Tango inheritance

---

src/sardana/tango/core/SardanaDevice.py
src/sardana/tango/pool/Pool.py

Reverts sardana-org/sardana#1214.
The above commit [broke](https://travis-ci.org/sardana-org/sardana/jobs/657212175?utm_medium=notification&utm_source=email) tests on Travis.
The PR tests were green but the PR branch was very outdatad and the tests were run agains docker image with outdated taurus.
In the current situation the tests unfortuatelly fails. I will automatically merge this one whenever it is green.

Revert "Fix Tango inheritance"

---

src/sardana/pool/poolcontrollers/DummyMotorController.py

This is a very trivial change. If travis CI is green I will auto-merge it.

Fix exception raising (Py3) in dummy mot

---

src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py

Use ParamParser in MacroButton.
This fix was actually proposed by @stanislaw55 in https://github.com/sardana-org/sardana/issues/1172#issuecomment-514077542. I just submitted the PR. Since I reviewed, tested and agree with this solution I will auto-merge it.

Fix MacroButton with repeat parameters (#1172)

---

src/sardana/macroserver/macros/standard.py

Use the motor API to read the dial position instead of the Tango API.
It solves #929

Read dial position from the motor API

---

src/sardana/macroserver/macro.py
src/sardana/spock/spockms.py
src/sardana/tango/macroserver/Door.py

It contains workaround for #1319

add a check for type keyword in spockms

---

doc/source/devel/api/api_sardana.rst
doc/source/devel/api/sardana/taurus/qt/qtcore/tango/sardana.rst
doc/source/users/taurus/index.rst

Add direct links to Sardana-Taurus model API

---

doc/source/users/overview.rst

typo in overview?

---

src/sardana/pool/poolmeasurementgroup.py
src/sardana/tango/pool/MeasurementGroup.py

Remove StartMultiple MeasurementGroup's command and all the underneath implementation from the core.
Fixes #996.

Remove StartMultiple MeasurementGroup's command

---

src/sardana/macroserver/macros/standard.py

parse dial position to nan in wa macro if motor position is None

---

src/sardana/macroserver/macros/scan.py

small fix for the `scanStats` macro to correctly calc the FWHM for badly sampled data

fix FWHM calculation

---

src/sardana/macroserver/macros/demo.py

Fixes #397
@sardana-org/integrators I will not bother you with the review and auto-merge it.

Remove mym2 macro (not working, demo macro)

---

src/sardana/macroserver/scan/gscan.py

Adds the missing delay parameter in position domain in the CTScan.

Fix delay description in position domain

---

doc/source/devel/howto_macros/macros_general.rst

Document Tango connection recycling and disposal.

---

src/sardana/macroserver/macro.py

Fix copy&paste mistake in docstring.
Fixes #1444
It is an obvious copy&paste correction hence I will merge myself.

Fix createMacro and prepareMacro docstring

---

src/sardana/spock/magic.py

Fix #1477: Launch showscan executable directly

---

src/sardana/macroserver/msenvmanager.py

This is an improved version of #1514 which was finally reverted in #1517.
Empty environments used with the dumb backend, when this is never correctly closed [*],
fails to open with the 'w' flag. This is because the `.dir` file is never created
and it is necessary to determine the backend by the `dbm.whichdb()`.
Avoid this problem by always closing the dbm. Actually this is only necessary for
the dumb backend but do it for gnu as well - it does not harm and makes the code
cleaner.
[*] The MacroServer process currently crashes at exit - see: sardana-org/sardana#719
Fixes #1425.

Fix msenvironment when empty and used with dumb backend

---

src/sardana/tango/core/SardanaDevice.py
src/sardana/tango/pool/Pool.py

This is a retry of #1214 proposed by @tiagocoutinho which was initially merged and then reverted in #1301.

Use LatestDeviceImpl (Device_5Impl)

---

src/sardana/macroserver/macros/standard.py

Should fix #1529 in the wm macro.
Are there other locations where one would like to apply this?

also apply position formatting to the limits

---

src/sardana/macroserver/macros/discrete.py
src/sardana/macroserver/scan/gscan.py
src/sardana/pool/poolcontrollers/TaurusController.py
src/sardana/spock/spockms.py
src/sardana/taurus/qt/qtgui/extra_macroexecutor/scanplotter.py
src/sardana/taurus/qt/qtgui/extra_pool/poolchannel.py
src/sardana/taurus/qt/qtgui/extra_pool/poolioregister.py
src/sardana/tools/config/get_pool_config.py

Remove usage of taurus deprecated features:
- `TaurusAttributeValue.value` -> `TaurusAttributeValue.rvalue`
- `getIcon()` -> `Qt.QIcon()`

Remove usage of taurus deprecated features

---

doc/source/users/getting_started/installing.rst

Improve installation instructions in the docs:
- add conda option
- recommend pip on Windows
- update Debian installation
- rewrite dependencies section
Fixes #727

Improve installation instructions

---

doc/source/users/standard_macro_catalog.rst
src/sardana/macroserver/macros/lists.py

Add macro to list Pools to which the MacroServer is connected.
@sardana-org/integrators this is a trivial PR, unless someone is against adding this macro, I will auto-merge.

Add lsp macro

---

src/sardana/tango/pool/MeasurementGroup.py

Changed some attributes on measurement group to not be memorized.

not memorize measurement group attrs like integration time etc.

---

.devcontainer/devcontainer.json
.devcontainer/sardana_dev/Dockerfile
.devcontainer/sardana_dev/environment.yml

The improvements of this PR are:
- Adds the Git Graph and Git Lens extensions to the VS Code. This allows a better workflow using Git, and moving between branches.
- Adds autopep8 and flake8 linter and autoformat to the environment, these packages are used by VS Code to format and lint the code.
- Adds ssh package allowing to push to repositories using ssh+git protocol.

Improve devcontainer

---

src/sardana/macroserver/macros/standard.py

update doc string of pos parameter in set_pos and set_user_pos

---

src/sardana/macroserver/macros/standard.py

limit checking for making sure that limits don't accept maximum lower than the minimum and adding try except blocks 
fixes #267

put in limit checks

---

src/sardana/macroserver/macros/standard.py

Respect enabled flag in `uct` macro

---

src/sardana/macroserver/msmacromanager.py
src/sardana/pool/poolmeasurementgroup.py
src/sardana/taurus/core/tango/sardana/pool.py
src/sardana/util/funcgenerator.py

Fixes #1619.
Related PR in Taurus [here](https://gitlab.com/taurus-org/taurus/-/merge_requests/1203).

Fix abort macro without stop

---

src/sardana/taurus/qt/qtgui/extra_macroexecutor/macrobutton.py

- MacroButton: Show 'State' info at tooltip
It fixes #656

Fix #656 (Add information to macrobutton tooltip)

---

src/sardana/spock/ipython_01_00/genutils.py
src/sardana/spock/magic.py
src/sardana/spock/spockms.py
src/sardana/util/graphics.py

Fixes #1106 
Enables to run spock without an X-session

add support for running without an X-session

---

src/sardana/macroserver/msmacromanager.py

Macros are executed in worker threads of a ThreadPool of size 10.
Each macro may end up being executed by a different thread.
In the investigation of #1095 we observed that memory allocated
in small chunks in different threads is not released to the OS.
Reduce the memory consumption by always executing macros
in the same thread (per door).
With this PR the 8 repetitions of:
```
for i in range(10): 
%ascan mot01 0 100 100 0.001
```
does not exceed (+/-) the memory used by the first scan already:
While in the develop branch (the same tests) it keeps growing:
Regarding the tests using the develop branch, I'm not sure the memory grows only until the amount of the memory of one scan multiplied by the number of worker threads (10) or until filling the available memory (there was no more free …

fix: reduce memory leak of scans
